"""Consolidated Stage 2 module.

Generated by module consolidation; public behavior is preserved.
"""

from __future__ import annotations


# ---- from schemas.py ----


from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Literal, Optional


class ArtifactType(str, Enum):
    text_span = "text_span"
    numeric_fact = "numeric_fact"
    table = "table"
    table_cell = "table_cell"
    figure = "figure"
    caption = "caption"
    visual_observation = "visual_observation"


class Modality(str, Enum):
    text = "text"
    image = "image"
    table = "table"
    figure = "figure"
    numeric = "numeric"


class ProvenanceOp(str, Enum):
    atom = "ATOM"
    and_op = "AND"
    or_op = "OR"


ValidationStatus = Literal["candidate", "schema_valid", "anchored", "discarded"]
AnchorType = Literal[
    "text_block",
    "layout_block",
    "full_page_image",
    "table_cell",
    "figure_region",
]
LayoutBlockType = Literal["text_block", "full_page_image"]

ALLOWED_VALIDATION_STATUSES = {"candidate", "schema_valid", "anchored", "discarded"}
ALLOWED_ANCHOR_TYPES = {
    "text_block",
    "layout_block",
    "full_page_image",
    "table_cell",
    "figure_region",
}
ALLOWED_LAYOUT_BLOCK_TYPES = {"text_block", "full_page_image"}


@dataclass
class Provenance:
    op: ProvenanceOp
    sources: List[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.op = _coerce_enum(self.op, ProvenanceOp, "op")
        if not self.sources:
            raise ValueError("provenance.sources must not be empty")

    def to_dict(self) -> Dict[str, Any]:
        return _enum_to_value(asdict(self))


@dataclass
class SourceAnchor:
    source_id: str
    anchor_type: AnchorType
    page_index: int
    bbox: Optional[List[float]] = None

    def __post_init__(self) -> None:
        if self.anchor_type not in ALLOWED_ANCHOR_TYPES:
            raise ValueError(f"Unsupported anchor_type: {self.anchor_type!r}")
        self.page_index = _coerce_page_index(self.page_index)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class EvidenceArtifact:
    artifact_id: str
    doc_id: str
    page_index: int
    artifact_type: ArtifactType
    modality: Modality
    content: str
    normalized_content: Dict[str, Any] = field(default_factory=dict)
    source_anchors: List[SourceAnchor] = field(default_factory=list)
    provenance: Optional[Provenance] = None
    validation_status: ValidationStatus = "candidate"
    compiler_metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.page_index = _coerce_page_index(self.page_index)
        self.artifact_type = _coerce_enum(self.artifact_type, ArtifactType, "artifact_type")
        self.modality = _coerce_enum(self.modality, Modality, "modality")
        if self.validation_status not in ALLOWED_VALIDATION_STATUSES:
            raise ValueError(f"Unsupported validation_status: {self.validation_status!r}")
        if not self.content:
            raise ValueError("content must not be empty")

    def to_dict(self) -> Dict[str, Any]:
        return _enum_to_value(asdict(self))


@dataclass
class PageArtifactOutput:
    doc_id: str
    page_index: int
    artifacts: List[EvidenceArtifact] = field(default_factory=list)
    uncertain_or_unreadable: List[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.page_index = _coerce_page_index(self.page_index)

    def to_dict(self) -> Dict[str, Any]:
        return _enum_to_value(asdict(self))


@dataclass
class LayoutBlock:
    block_id: str
    block_type: LayoutBlockType
    page_index: int
    bbox: Optional[List[float]] = None
    text: Optional[str] = None

    def __post_init__(self) -> None:
        if self.block_type not in ALLOWED_LAYOUT_BLOCK_TYPES:
            raise ValueError(f"Unsupported block_type: {self.block_type!r}")
        self.page_index = _coerce_page_index(self.page_index)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PageCompilationInput:
    doc_id: str
    page_index: int
    page_text: Optional[str]
    page_text_path: Optional[str]
    page_image_path: Optional[str]
    has_page_text: bool
    has_page_image: bool
    layout_blocks: List[LayoutBlock] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.page_index = _coerce_page_index(self.page_index)

    def to_dict(self) -> Dict[str, Any]:
        return _enum_to_value(asdict(self))


def _coerce_page_index(value: Any) -> int:
    if isinstance(value, bool):
        raise ValueError(f"Invalid boolean page_index: {value!r}")
    page_index = int(value)
    if page_index < 0:
        raise ValueError(f"Invalid negative page_index: {value!r}")
    return page_index


def _coerce_enum(value: Any, enum_type: type[Enum], field_name: str) -> Enum:
    if isinstance(value, enum_type):
        return value
    try:
        return enum_type(value)
    except ValueError as exc:
        raise ValueError(f"Unsupported {field_name}: {value!r}") from exc


def _enum_to_value(value: Any) -> Any:
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, dict):
        return {key: _enum_to_value(child) for key, child in value.items()}
    if isinstance(value, list):
        return [_enum_to_value(child) for child in value]
    return value

# ---- from schema_serialization.py ----


from typing import Any, Dict, List


def get_allowed_artifact_types() -> List[str]:
    return [item.value for item in ArtifactType]


def get_allowed_modalities() -> List[str]:
    return [item.value for item in Modality]


def get_allowed_provenance_ops() -> List[str]:
    return [item.value for item in ProvenanceOp]


def get_allowed_anchor_types() -> List[str]:
    return sorted(ALLOWED_ANCHOR_TYPES)


def get_allowed_validation_statuses() -> List[str]:
    return sorted(ALLOWED_VALIDATION_STATUSES)


def build_evidence_artifact_schema_dict() -> Dict[str, Any]:
    """Return a JSON-schema-like dict for one EvidenceArtifact."""

    return {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "artifact_id",
            "doc_id",
            "page_index",
            "artifact_type",
            "modality",
            "content",
            "normalized_content",
            "source_anchors",
            "provenance",
            "validation_status",
            "compiler_metadata",
        ],
        "properties": {
            "artifact_id": {"type": "string", "minLength": 1},
            "doc_id": {"type": "string", "minLength": 1},
            "page_index": {"type": "integer", "minimum": 0},
            "artifact_type": {
                "type": "string",
                "enum": get_allowed_artifact_types(),
            },
            "modality": {
                "type": "string",
                "enum": get_allowed_modalities(),
            },
            "content": {"type": "string", "minLength": 1, "maxLength": 1200},
            "normalized_content": {"type": "object"},
            "source_anchors": {
                "type": "array",
                "minItems": 1,
                "items": build_source_anchor_schema_dict(),
            },
            "provenance": build_provenance_schema_dict(),
            "validation_status": {
                "type": "string",
                "enum": get_allowed_validation_statuses(),
            },
            "compiler_metadata": {"type": "object"},
        },
    }


def build_page_artifact_output_schema_dict() -> Dict[str, Any]:
    """Return a JSON-schema-like dict for one PageArtifactOutput."""

    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["doc_id", "page_index", "artifacts"],
        "properties": {
            "doc_id": {"type": "string", "minLength": 1},
            "page_index": {"type": "integer", "minimum": 0},
            "artifacts": {
                "type": "array",
                "items": build_evidence_artifact_schema_dict(),
            },
            "uncertain_or_unreadable": {
                "type": "array",
                "items": {"type": "string"},
            },
        },
    }


def build_source_anchor_schema_dict() -> Dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["source_id", "anchor_type", "page_index", "bbox"],
        "properties": {
            "source_id": {"type": "string", "minLength": 1},
            "anchor_type": {
                "type": "string",
                "enum": get_allowed_anchor_types(),
            },
            "page_index": {"type": "integer", "minimum": 0},
            "bbox": {
                "anyOf": [
                    {"type": "null"},
                    {
                        "type": "array",
                        "items": {"type": "number"},
                    },
                ]
            },
        },
    }


def build_provenance_schema_dict() -> Dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["op", "sources"],
        "properties": {
            "op": {
                "type": "string",
                "enum": get_allowed_provenance_ops(),
            },
            "sources": {
                "type": "array",
                "minItems": 1,
                "items": {"type": "string", "minLength": 1},
            },
        },
    }

# ---- from validation_errors.py ----


from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, Optional


class ValidationErrorType(str, Enum):
    schema_invalid = "schema_invalid"
    missing_required_field = "missing_required_field"
    invalid_enum_value = "invalid_enum_value"
    invalid_page_index = "invalid_page_index"
    empty_content = "empty_content"
    missing_source_anchor = "missing_source_anchor"
    source_anchor_not_found = "source_anchor_not_found"
    provenance_source_not_found = "provenance_source_not_found"
    duplicate_artifact = "duplicate_artifact"
    invalid_validation_status = "invalid_validation_status"
    invalid_artifact_id = "invalid_artifact_id"
    invalid_output_container = "invalid_output_container"


@dataclass
class ValidationIssue:
    error_type: ValidationErrorType
    message: str
    doc_id: Optional[str] = None
    page_index: Optional[int] = None
    artifact_id: Optional[str] = None
    field_path: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not isinstance(self.error_type, ValidationErrorType):
            self.error_type = ValidationErrorType(self.error_type)
        if self.details is None:
            self.details = {}
        if not isinstance(self.details, dict):
            raise ValueError("ValidationIssue.details must be a dict")

    def to_dict(self) -> Dict[str, Any]:
        issue_dict = asdict(self)
        issue_dict["error_type"] = self.error_type.value
        return issue_dict
