"""Consolidated Stage 2 module.

Generated by module consolidation; public behavior is preserved.
"""

from __future__ import annotations


# ---- from artifact_deduplicator.py ----


import json
from typing import Any


def normalize_for_hash(value: Any) -> str:
    """Return a stable string representation for deduplication keys."""

    if isinstance(value, str):
        return " ".join(value.strip().lower().split())
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def build_artifact_dedup_key(artifact: dict) -> str:
    """Build the fixed Stage 2 artifact deduplication key."""

    source_ids = sorted(
        str(anchor.get("source_id"))
        for anchor in artifact.get("source_anchors", []) or []
        if isinstance(anchor, dict) and anchor.get("source_id") is not None
    )
    normalized_content = artifact.get("normalized_content")
    content_key = normalized_content if normalized_content else artifact.get("content")
    key = {
        "doc_id": artifact.get("doc_id"),
        "page_index": artifact.get("page_index"),
        "artifact_type": artifact.get("artifact_type"),
        "modality": artifact.get("modality"),
        "source_ids": source_ids,
        "content": normalize_for_hash(content_key),
    }
    return json.dumps(key, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def deduplicate_page_artifacts(page_output: dict) -> tuple[dict, list[dict]]:
    """Drop duplicate candidate artifacts while preserving the first instance."""

    deduped_output = dict(page_output)
    artifacts = page_output.get("artifacts", [])
    if not isinstance(artifacts, list):
        deduped_output["artifacts"] = artifacts
        return deduped_output, []

    kept_artifacts = []
    removed = []
    first_by_key: dict[str, dict] = {}
    for artifact in artifacts:
        if not isinstance(artifact, dict):
            kept_artifacts.append(artifact)
            continue
        dedup_key = build_artifact_dedup_key(artifact)
        if dedup_key not in first_by_key:
            first_by_key[dedup_key] = artifact
            kept_artifacts.append(artifact)
            continue
        kept = first_by_key[dedup_key]
        removed.append(
            {
                "error_type": "duplicate_artifact_deduplicated",
                "artifact_id": artifact.get("artifact_id"),
                "duplicate_of": kept.get("artifact_id"),
                "dedup_key": dedup_key,
                "doc_id": artifact.get("doc_id"),
                "page_index": artifact.get("page_index"),
            }
        )

    deduped_output["artifacts"] = kept_artifacts
    return deduped_output, removed

# ---- from artifact_validator.py ----


from collections import defaultdict
from typing import Any, Dict, List, Set, Tuple

from .artifact_schema import (
    get_allowed_anchor_types,
    get_allowed_artifact_types,
    get_allowed_modalities,
    get_allowed_provenance_ops,
    get_allowed_validation_statuses,
)
from .artifact_schema import ValidationErrorType, ValidationIssue


PAGE_OUTPUT_ALLOWED_FIELDS = {"doc_id", "page_index", "artifacts", "uncertain_or_unreadable"}


ARTIFACT_REQUIRED_FIELDS = [
    "artifact_id",
    "doc_id",
    "page_index",
    "artifact_type",
    "modality",
    "content",
    "normalized_content",
    "source_anchors",
    "provenance",
    "validation_status",
    "compiler_metadata",
]


def validate_page_artifact_output_schema(
    raw_output: Dict[str, Any],
) -> Tuple[bool, List[ValidationIssue]]:
    """Validate only the page-level output container shape."""

    issues: List[ValidationIssue] = []
    if not isinstance(raw_output, dict):
        return False, [
            ValidationIssue(
                error_type=ValidationErrorType.invalid_output_container,
                message="Page artifact output must be a dict.",
                field_path="$",
                details={"observed_type": type(raw_output).__name__},
            )
        ]

    for field_name in sorted(set(raw_output) - PAGE_OUTPUT_ALLOWED_FIELDS):
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_output_container,
                message=f"Unexpected page output field: {field_name}",
                doc_id=_safe_doc_id(raw_output),
                page_index=_safe_page_index(raw_output),
                field_path=field_name,
                details={"unexpected_field": field_name},
            )
        )

    for field_name in ("doc_id", "page_index", "artifacts"):
        if field_name not in raw_output:
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.missing_required_field,
                    message=f"Missing required page output field: {field_name}",
                    doc_id=_safe_doc_id(raw_output),
                    page_index=_safe_page_index(raw_output),
                    field_path=field_name,
                    details={"missing_field": field_name},
                )
            )

    if "artifacts" in raw_output and not isinstance(raw_output["artifacts"], list):
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_output_container,
                message="Page output artifacts must be a list.",
                doc_id=_safe_doc_id(raw_output),
                page_index=_safe_page_index(raw_output),
                field_path="artifacts",
                details={"observed_type": type(raw_output["artifacts"]).__name__},
            )
        )

    if (
        "uncertain_or_unreadable" in raw_output
        and not isinstance(raw_output["uncertain_or_unreadable"], list)
    ):
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_output_container,
                message="uncertain_or_unreadable must be a list when present.",
                doc_id=_safe_doc_id(raw_output),
                page_index=_safe_page_index(raw_output),
                field_path="uncertain_or_unreadable",
                details={
                    "observed_type": type(raw_output["uncertain_or_unreadable"]).__name__,
                },
            )
        )

    if "page_index" in raw_output and not _is_non_negative_int(raw_output["page_index"]):
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_page_index,
                message="Page output page_index must be a non-negative integer.",
                doc_id=_safe_doc_id(raw_output),
                page_index=_safe_page_index(raw_output),
                field_path="page_index",
                details={"observed_value": raw_output.get("page_index")},
            )
        )

    return not issues, issues


def validate_evidence_artifact_schema(
    raw_artifact: Dict[str, Any],
    doc_id: str,
    page_index: int,
) -> List[ValidationIssue]:
    """Validate one artifact dict against Stage 2 deterministic rules."""

    if not isinstance(raw_artifact, dict):
        return [
            ValidationIssue(
                error_type=ValidationErrorType.schema_invalid,
                message="Evidence artifact must be a dict.",
                doc_id=doc_id,
                page_index=page_index,
                field_path="artifacts[]",
                details={"observed_type": type(raw_artifact).__name__},
            )
        ]

    issues: List[ValidationIssue] = []
    artifact_id = raw_artifact.get("artifact_id")

    for field_name in ARTIFACT_REQUIRED_FIELDS:
        if field_name not in raw_artifact:
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.missing_required_field,
                    message=f"Missing required artifact field: {field_name}",
                    doc_id=doc_id,
                    page_index=page_index,
                    artifact_id=artifact_id,
                    field_path=field_name,
                    details={"missing_field": field_name},
                )
            )

    for field_name in sorted(set(raw_artifact) - set(ARTIFACT_REQUIRED_FIELDS)):
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.schema_invalid,
                message=f"Unexpected artifact field: {field_name}",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path=field_name,
                details={"unexpected_field": field_name},
            )
        )

    if issues:
        return issues

    if not isinstance(raw_artifact["artifact_id"], str) or not raw_artifact["artifact_id"].strip():
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_artifact_id,
                message="artifact_id must be a non-empty string.",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path="artifact_id",
                details={"observed_value": raw_artifact.get("artifact_id")},
            )
        )

    if raw_artifact["doc_id"] != doc_id:
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.schema_invalid,
                message="artifact.doc_id must match page output doc_id.",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path="doc_id",
                details={"observed_value": raw_artifact.get("doc_id"), "expected_value": doc_id},
            )
        )

    if raw_artifact["page_index"] != page_index:
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_page_index,
                message="artifact.page_index must match page output page_index.",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path="page_index",
                details={
                    "observed_value": raw_artifact.get("page_index"),
                    "expected_value": page_index,
                },
            )
        )

    if raw_artifact["artifact_type"] not in get_allowed_artifact_types():
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_enum_value,
                message="artifact_type is not allowed.",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path="artifact_type",
                details={"observed_value": raw_artifact.get("artifact_type")},
            )
        )

    if raw_artifact["modality"] not in get_allowed_modalities():
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_enum_value,
                message="modality is not allowed.",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path="modality",
                details={"observed_value": raw_artifact.get("modality")},
            )
        )

    if raw_artifact["validation_status"] not in get_allowed_validation_statuses():
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.invalid_validation_status,
                message="validation_status is not allowed.",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path="validation_status",
                details={"observed_value": raw_artifact.get("validation_status")},
            )
        )

    if not isinstance(raw_artifact["content"], str) or not raw_artifact["content"].strip():
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.empty_content,
                message="content must be a non-empty string.",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path="content",
                details={"observed_type": type(raw_artifact.get("content")).__name__},
            )
        )

    if not isinstance(raw_artifact["normalized_content"], dict):
        issues.append(_schema_type_issue(raw_artifact, doc_id, page_index, "normalized_content", "dict"))

    if not isinstance(raw_artifact["compiler_metadata"], dict):
        issues.append(_schema_type_issue(raw_artifact, doc_id, page_index, "compiler_metadata", "dict"))

    if not isinstance(raw_artifact["source_anchors"], list) or not raw_artifact["source_anchors"]:
        issues.append(
            ValidationIssue(
                error_type=ValidationErrorType.missing_source_anchor,
                message="source_anchors must be a non-empty list.",
                doc_id=doc_id,
                page_index=page_index,
                artifact_id=artifact_id,
                field_path="source_anchors",
                details={"observed_type": type(raw_artifact.get("source_anchors")).__name__},
            )
        )

    provenance = raw_artifact["provenance"]
    if not isinstance(provenance, dict):
        issues.append(_schema_type_issue(raw_artifact, doc_id, page_index, "provenance", "dict"))
    else:
        if "op" not in provenance:
            issues.append(_missing_nested_issue(raw_artifact, doc_id, page_index, "provenance.op"))
        elif provenance["op"] not in get_allowed_provenance_ops():
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.invalid_enum_value,
                    message="provenance.op is not allowed.",
                    doc_id=doc_id,
                    page_index=page_index,
                    artifact_id=artifact_id,
                    field_path="provenance.op",
                    details={"observed_value": provenance.get("op")},
                )
            )
        if "sources" not in provenance:
            issues.append(_missing_nested_issue(raw_artifact, doc_id, page_index, "provenance.sources"))
        elif not isinstance(provenance["sources"], list) or not provenance["sources"]:
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.schema_invalid,
                    message="provenance.sources must be a non-empty list.",
                    doc_id=doc_id,
                    page_index=page_index,
                    artifact_id=artifact_id,
                    field_path="provenance.sources",
                    details={"observed_type": type(provenance.get("sources")).__name__},
                )
            )

    return issues


def validate_source_anchors(
    raw_artifact: Dict[str, Any],
    layout_blocks: List[Dict[str, Any]],
) -> List[ValidationIssue]:
    """Validate artifact source anchors against available layout blocks."""

    issues: List[ValidationIssue] = []
    artifact_id = raw_artifact.get("artifact_id")
    doc_id = raw_artifact.get("doc_id")
    page_index = raw_artifact.get("page_index")
    valid_source_ids = _layout_block_ids(layout_blocks)
    source_anchors = raw_artifact.get("source_anchors")
    if not isinstance(source_anchors, list):
        return issues

    for anchor_index, anchor in enumerate(source_anchors):
        field_prefix = f"source_anchors[{anchor_index}]"
        if not isinstance(anchor, dict):
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.schema_invalid,
                    message="source_anchor must be a dict.",
                    doc_id=doc_id,
                    page_index=page_index,
                    artifact_id=artifact_id,
                    field_path=field_prefix,
                    details={"observed_type": type(anchor).__name__},
                )
            )
            continue

        source_id = anchor.get("source_id")
        if source_id not in valid_source_ids:
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.source_anchor_not_found,
                    message="source_anchor.source_id was not found in layout_blocks.",
                    doc_id=doc_id,
                    page_index=page_index,
                    artifact_id=artifact_id,
                    field_path=f"{field_prefix}.source_id",
                    details={"source_id": source_id},
                )
            )
        if anchor.get("page_index") != page_index:
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.invalid_page_index,
                    message="source_anchor.page_index must match artifact.page_index.",
                    doc_id=doc_id,
                    page_index=page_index,
                    artifact_id=artifact_id,
                    field_path=f"{field_prefix}.page_index",
                    details={
                        "observed_value": anchor.get("page_index"),
                        "expected_value": page_index,
                    },
                )
            )
        if anchor.get("anchor_type") not in get_allowed_anchor_types():
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.invalid_enum_value,
                    message="source_anchor.anchor_type is not allowed.",
                    doc_id=doc_id,
                    page_index=page_index,
                    artifact_id=artifact_id,
                    field_path=f"{field_prefix}.anchor_type",
                    details={"observed_value": anchor.get("anchor_type")},
                )
            )

    return issues


def validate_provenance(
    raw_artifact: Dict[str, Any],
    layout_blocks: List[Dict[str, Any]],
) -> List[ValidationIssue]:
    """Validate provenance source ids against available layout blocks."""

    provenance = raw_artifact.get("provenance")
    if not isinstance(provenance, dict) or not isinstance(provenance.get("sources"), list):
        return []

    issues: List[ValidationIssue] = []
    valid_source_ids = _layout_block_ids(layout_blocks)
    for source_index, source_id in enumerate(provenance["sources"]):
        if source_id not in valid_source_ids:
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.provenance_source_not_found,
                    message="provenance source id was not found in layout_blocks.",
                    doc_id=raw_artifact.get("doc_id"),
                    page_index=raw_artifact.get("page_index"),
                    artifact_id=raw_artifact.get("artifact_id"),
                    field_path=f"provenance.sources[{source_index}]",
                    details={"source_id": source_id},
                )
            )
    return issues


def detect_duplicate_artifacts(raw_artifacts: List[Dict[str, Any]]) -> List[ValidationIssue]:
    """Detect deterministic duplicate artifacts by page, type, content, anchors."""

    grouped_artifacts: Dict[Tuple[Any, Any, str, Tuple[str, ...]], List[Dict[str, Any]]] = defaultdict(list)
    for raw_artifact in raw_artifacts:
        if not isinstance(raw_artifact, dict):
            continue
        key = (
            raw_artifact.get("page_index"),
            raw_artifact.get("artifact_type"),
            _normalize_content(raw_artifact.get("content")),
            _source_anchor_id_tuple(raw_artifact.get("source_anchors")),
        )
        grouped_artifacts[key].append(raw_artifact)

    issues: List[ValidationIssue] = []
    for duplicate_group in grouped_artifacts.values():
        if len(duplicate_group) <= 1:
            continue
        artifact_ids = [item.get("artifact_id") for item in duplicate_group]
        for raw_artifact in duplicate_group[1:]:
            issues.append(
                ValidationIssue(
                    error_type=ValidationErrorType.duplicate_artifact,
                    message="Duplicate artifact detected.",
                    doc_id=raw_artifact.get("doc_id"),
                    page_index=raw_artifact.get("page_index"),
                    artifact_id=raw_artifact.get("artifact_id"),
                    field_path="artifacts",
                    details={"duplicate_artifact_ids": artifact_ids},
                )
            )
    return issues


def validate_page_artifact_output(
    raw_output: Dict[str, Any],
    layout_blocks: List[Dict[str, Any]],
) -> Tuple[List[Dict[str, Any]], List[ValidationIssue]]:
    """Validate a page output and return anchored artifacts plus issues."""

    container_valid, issues = validate_page_artifact_output_schema(raw_output)
    if not container_valid:
        return [], issues

    doc_id = raw_output["doc_id"]
    page_index = raw_output["page_index"]
    artifact_issues_by_id: Dict[int, List[ValidationIssue]] = {}
    artifacts = raw_output.get("artifacts", [])

    for index, raw_artifact in enumerate(artifacts):
        artifact_issues = validate_evidence_artifact_schema(raw_artifact, doc_id, page_index)
        if not artifact_issues:
            artifact_issues.extend(validate_source_anchors(raw_artifact, layout_blocks))
            artifact_issues.extend(validate_provenance(raw_artifact, layout_blocks))
        artifact_issues_by_id[index] = artifact_issues
        issues.extend(artifact_issues)

    duplicate_issues = detect_duplicate_artifacts(artifacts)
    duplicate_artifact_ids = {issue.artifact_id for issue in duplicate_issues}
    issues.extend(duplicate_issues)

    valid_artifacts: List[Dict[str, Any]] = []
    for index, raw_artifact in enumerate(artifacts):
        if artifact_issues_by_id.get(index):
            continue
        if raw_artifact.get("artifact_id") in duplicate_artifact_ids:
            continue
        anchored_artifact = dict(raw_artifact)
        anchored_artifact["validation_status"] = "anchored"
        valid_artifacts.append(anchored_artifact)

    return valid_artifacts, issues


def _schema_type_issue(
    raw_artifact: Dict[str, Any],
    doc_id: str,
    page_index: int,
    field_path: str,
    expected_type: str,
) -> ValidationIssue:
    return ValidationIssue(
        error_type=ValidationErrorType.schema_invalid,
        message=f"{field_path} must be a {expected_type}.",
        doc_id=doc_id,
        page_index=page_index,
        artifact_id=raw_artifact.get("artifact_id"),
        field_path=field_path,
        details={"observed_type": type(raw_artifact.get(field_path)).__name__},
    )


def _missing_nested_issue(
    raw_artifact: Dict[str, Any],
    doc_id: str,
    page_index: int,
    field_path: str,
) -> ValidationIssue:
    return ValidationIssue(
        error_type=ValidationErrorType.missing_required_field,
        message=f"Missing required artifact field: {field_path}",
        doc_id=doc_id,
        page_index=page_index,
        artifact_id=raw_artifact.get("artifact_id"),
        field_path=field_path,
        details={"missing_field": field_path},
    )


def _layout_block_ids(layout_blocks: List[Dict[str, Any]]) -> Set[Any]:
    return {block.get("block_id") for block in layout_blocks if isinstance(block, dict)}


def _normalize_content(content: Any) -> str:
    if content is None:
        return ""
    return " ".join(str(content).strip().lower().split())


def _source_anchor_id_tuple(source_anchors: Any) -> Tuple[str, ...]:
    if not isinstance(source_anchors, list):
        return tuple()
    source_ids = [anchor.get("source_id") for anchor in source_anchors if isinstance(anchor, dict)]
    return tuple(sorted(str(source_id) for source_id in source_ids))


def _safe_doc_id(raw_output: Dict[str, Any]) -> Any:
    if isinstance(raw_output, dict):
        return raw_output.get("doc_id")
    return None


def _safe_page_index(raw_output: Dict[str, Any]) -> Any:
    if isinstance(raw_output, dict) and _is_non_negative_int(raw_output.get("page_index")):
        return raw_output.get("page_index")
    return None


def _is_non_negative_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and value >= 0

# ---- from artifact_store.py ----


import json
from pathlib import Path
import inspect
from typing import Any, Dict, List


DEFAULT_COMPILER_METADATA = {
    "compiler_name": "mock_stage2_dry_run",
    "compiler_version": "mock_stage2_dry_run",
    "schema_version": "stage2_artifact_schema_v1",
    "model_name": "mock",
    "temperature": None,
    "max_repair_attempts": 0,
}


def build_artifact_index(pages: List[Dict[str, Any]]) -> Dict[str, Dict[str, List[str]]]:
    """Build deterministic artifact indexes by type and page index."""

    by_artifact_type: Dict[str, List[str]] = {}
    by_page_index: Dict[str, List[str]] = {}
    for page in pages:
        page_index_key = str(page["page_index"])
        for artifact in page.get("artifacts", []):
            artifact_id = artifact["artifact_id"]
            artifact_type = artifact["artifact_type"]
            by_artifact_type.setdefault(artifact_type, []).append(artifact_id)
            by_page_index.setdefault(page_index_key, []).append(artifact_id)

    return {
        "by_artifact_type": _sort_index_values(by_artifact_type),
        "by_page_index": _sort_index_values(by_page_index),
    }


def compute_compilation_statistics(pages: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Compute document-level Stage 2 compilation statistics."""

    num_pages_compiled = len(pages)
    num_pages_with_layout_blocks = sum(1 for page in pages if page.get("layout_blocks"))
    num_pages_with_artifacts = sum(1 for page in pages if page.get("artifacts"))
    num_artifacts = sum(len(page.get("artifacts", [])) for page in pages)
    num_raw_artifacts = sum(
        page.get("page_compilation_statistics", {}).get("num_raw_artifacts", len(page.get("artifacts", [])))
        for page in pages
    )
    num_schema_valid_artifacts = sum(
        page.get("page_compilation_statistics", {}).get("num_schema_valid_artifacts", 0)
        for page in pages
    )
    num_anchored_artifacts = sum(
        page.get("page_compilation_statistics", {}).get("num_anchored_artifacts", 0)
        for page in pages
    )
    num_discarded_artifacts = sum(
        page.get("page_compilation_statistics", {}).get("num_discarded_artifacts", 0)
        for page in pages
    )
    num_explicit_constraint_pages_compiled = sum(
        1 for page in pages if page.get("_is_explicit_constraint_page", False)
    )
    num_retrieval_missed_explicit_pages_compiled = sum(
        1 for page in pages if page.get("_is_retrieval_missed_explicit_page", False)
    )

    denominator = max(1, num_raw_artifacts)
    return {
        "num_pages_compiled": num_pages_compiled,
        "num_pages_with_layout_blocks": num_pages_with_layout_blocks,
        "num_pages_with_artifacts": num_pages_with_artifacts,
        "num_artifacts": num_artifacts,
        "num_schema_valid_artifacts": num_schema_valid_artifacts,
        "num_anchored_artifacts": num_anchored_artifacts,
        "num_discarded_artifacts": num_discarded_artifacts,
        "schema_valid_rate": num_schema_valid_artifacts / denominator,
        "anchoring_rate": num_anchored_artifacts / denominator,
        "discard_rate": num_discarded_artifacts / denominator,
        "num_explicit_constraint_pages_compiled": num_explicit_constraint_pages_compiled,
        "num_retrieval_missed_explicit_pages_compiled": num_retrieval_missed_explicit_pages_compiled,
    }


def build_document_artifact_store(
    canonical_record: Dict[str, Any],
    prepared_pages: List[Dict[str, Any]],
    page_artifact_outputs: Dict[int, Dict[str, Any]],
    validation_results: Dict[int, Dict[str, Any]],
    compiler_metadata: Dict[str, Any],
) -> Dict[str, Any]:
    """Build a provenance-preserving document artifact store from valid artifacts."""

    doc_id = canonical_record["document"]["doc_id"]
    candidate_pool = canonical_record.get("candidate_pool", {})
    explicit_pages = set(candidate_pool.get("explicit_constraint_pages", []))
    missed_explicit_pages = set(candidate_pool.get("retrieval_missed_explicit_pages", []))
    compiler = _build_artifact_store_compiler_metadata(compiler_metadata)

    store_pages: List[Dict[str, Any]] = []
    for prepared_page in prepared_pages:
        page_index = int(prepared_page["page_index"])
        raw_output = page_artifact_outputs.get(page_index, {})
        validation_result = validation_results.get(page_index, {})
        valid_artifacts = list(validation_result.get("valid_artifacts", []))
        num_raw_artifacts = len(raw_output.get("artifacts", [])) if isinstance(raw_output, dict) else 0
        num_schema_valid_artifacts = len(valid_artifacts)
        num_anchored_artifacts = sum(
            1 for artifact in valid_artifacts if artifact.get("validation_status") == "anchored"
        )
        num_discarded_artifacts = max(0, num_raw_artifacts - len(valid_artifacts))

        store_pages.append(
            {
                "page_index": page_index,
                "page_number_one_based": page_index + 1,
                "page_source": {
                    "page_text_path": prepared_page.get("page_text_path"),
                    "page_image_path": prepared_page.get("page_image_path"),
                },
                "layout_blocks": prepared_page.get("layout_blocks", []),
                "artifacts": valid_artifacts,
                "page_compilation_statistics": {
                    "num_raw_artifacts": num_raw_artifacts,
                    "num_schema_valid_artifacts": num_schema_valid_artifacts,
                    "num_anchored_artifacts": num_anchored_artifacts,
                    "num_discarded_artifacts": num_discarded_artifacts,
                },
                "_is_explicit_constraint_page": page_index in explicit_pages,
                "_is_retrieval_missed_explicit_page": page_index in missed_explicit_pages,
            }
        )

    compilation_statistics = compute_compilation_statistics(store_pages)
    for page in store_pages:
        page.pop("_is_explicit_constraint_page", None)
        page.pop("_is_retrieval_missed_explicit_page", None)

    return {
        "document": {
            "doc_id": doc_id,
            "dataset": canonical_record["document"].get("dataset"),
            "page_index_base": 0,
        },
        "compiler": compiler,
        "pages": store_pages,
        "artifact_index": build_artifact_index(store_pages),
        "compilation_statistics": compilation_statistics,
    }


def write_artifact_store(store: Dict[str, Any], output_path: str | Path) -> None:
    """Write an artifact store as pretty JSON."""

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(store, ensure_ascii=False, indent=2), encoding="utf-8")


def _build_artifact_store_compiler_metadata(compiler_metadata: Dict[str, Any]) -> Dict[str, Any]:
    compiler = dict(DEFAULT_COMPILER_METADATA)
    compiler.update(compiler_metadata or {})
    return {
        "compiler_name": compiler.get("compiler_name"),
        "compiler_version": compiler.get("compiler_version"),
        "schema_version": compiler.get("schema_version"),
        "model_name": compiler.get("model_name", "mock"),
        "temperature": compiler.get("temperature"),
        "max_repair_attempts": compiler.get("max_repair_attempts", 0),
    }


def _sort_index_values(index: Dict[str, List[str]]) -> Dict[str, List[str]]:
    return {key: sorted(value) for key, value in sorted(index.items(), key=lambda item: item[0])}

# ---- from artifact_compiler.py ----


from pathlib import Path
from typing import Any, Dict, List

from .provider import ArtifactCompilerClient
from .provider import (
    build_artifact_compiler_system_prompt,
    build_artifact_compiler_user_prompt,
)
from .logs import DiscardLogEntry, issue_to_discard_log_entry, write_discard_log_entry
from .logs import build_raw_output_log_entry, write_raw_output_log


def compile_page_with_client(
    canonical_record: Dict[str, Any],
    page_input: Dict[str, Any],
    client: ArtifactCompilerClient,
    schema_dict: Dict[str, Any],
    compiler_metadata: Dict[str, Any],
    raw_output_log_path: str | Path | None = None,
    discard_log_path: str | Path | None = None,
    compiler_version: str = "stage2_compiler_v1",
    prompt_version: str = "artifact_compiler_prompt_v1",
    deterministic_dedup_enabled: bool = True,
) -> Dict[str, Any]:
    """Compile one page with a client, then deterministically validate output."""

    system_prompt = build_artifact_compiler_system_prompt()
    user_prompt = build_artifact_compiler_user_prompt(
        canonical_record=canonical_record,
        page_input=page_input,
        schema_dict=schema_dict,
    )
    raw_output = _generate_page_artifacts_with_optional_page_input(
        client=client,
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        schema_dict=schema_dict,
        page_input=page_input,
    )
    if raw_output_log_path is not None:
        write_raw_output_log(
            raw_output_log_path,
            build_raw_output_log_entry(
                doc_id=page_input["doc_id"],
                page_index=int(page_input["page_index"]),
                provider=str(compiler_metadata.get("provider", compiler_metadata.get("compiler_name", "unknown"))),
                model_name=compiler_metadata.get("model_name"),
                compiler_version=compiler_version,
                prompt_version=prompt_version,
                raw_output=raw_output if isinstance(raw_output, dict) else {"raw_output": raw_output},
            ),
        )

    identity_normalized_output = _inject_runtime_artifact_identity(raw_output, page_input)
    num_raw_artifacts_before_dedup = _count_raw_artifacts(identity_normalized_output)
    dedup_removed: List[Dict[str, Any]] = []
    validation_input = identity_normalized_output
    if deterministic_dedup_enabled and isinstance(identity_normalized_output, dict):
        validation_input, dedup_removed = deduplicate_page_artifacts(identity_normalized_output)
        if discard_log_path is not None:
            for removed in dedup_removed:
                write_discard_log_entry(
                    discard_log_path,
                    DiscardLogEntry(
                        doc_id=page_input["doc_id"],
                        page_index=int(page_input["page_index"]),
                        artifact_id=removed.get("artifact_id"),
                        error_type="duplicate_artifact_deduplicated",
                        message="Duplicate artifact removed before deterministic validation.",
                        field_path="artifacts",
                        details={
                            "duplicate_of": removed.get("duplicate_of"),
                            "dedup_key": removed.get("dedup_key"),
                            "dedup_rule": "doc_id+page_index+artifact_type+modality+source_anchor_ids+content_hash",
                        },
                        stage="stage2_compiler_deterministic_dedup",
                        compiler_version=compiler_version,
                    ),
                )

    valid_artifacts, validation_issues = validate_page_artifact_output(
        raw_output=validation_input,
        layout_blocks=page_input.get("layout_blocks", []),
    )
    if discard_log_path is not None:
        for issue in validation_issues:
            write_discard_log_entry(
                discard_log_path,
                issue_to_discard_log_entry(
                    issue,
                    stage="stage2_compiler_validation",
                    compiler_version=compiler_version,
                ),
            )

    return {
        "page_index": page_input["page_index"],
        "raw_output": validation_input,
        "raw_output_before_dedup": raw_output,
        "valid_artifacts": valid_artifacts,
        "validation_issues": [issue.to_dict() for issue in validation_issues],
        "compilation_statistics": {
            "deterministic_dedup_enabled": bool(deterministic_dedup_enabled),
            "dedup_stage": "after_raw_output_log_before_validation" if deterministic_dedup_enabled else None,
            "dedup_rule": (
                "doc_id+page_index+artifact_type+modality+source_anchor_ids+content_hash"
                if deterministic_dedup_enabled
                else None
            ),
            "num_raw_artifacts_before_dedup": num_raw_artifacts_before_dedup,
            "num_deduplicated_artifacts": len(dedup_removed),
            "deduplicated_artifact_issue_type_count": len(dedup_removed),
            "num_raw_artifacts": _count_raw_artifacts(validation_input),
            "num_valid_artifacts": len(valid_artifacts),
            "num_validation_issues": len(validation_issues),
            "schema_valid_rate_before_dedup": _rate(len(valid_artifacts), num_raw_artifacts_before_dedup),
            "schema_valid_rate_after_dedup": _rate(len(valid_artifacts), _count_raw_artifacts(validation_input)),
            "discard_rate_before_dedup": _discard_rate(num_raw_artifacts_before_dedup, len(valid_artifacts)),
            "discard_rate_after_dedup": _discard_rate(_count_raw_artifacts(validation_input), len(valid_artifacts)),
        },
    }


def _inject_runtime_artifact_identity(raw_output: Any, page_input: Dict[str, Any]) -> Any:
    """Use runtime page context as the only source of artifact identity."""

    if not isinstance(raw_output, dict):
        return raw_output

    doc_id = page_input["doc_id"]
    page_index = int(page_input["page_index"])
    normalized_output = dict(raw_output)
    normalized_output["doc_id"] = doc_id
    normalized_output["page_index"] = page_index

    artifacts = raw_output.get("artifacts")
    if not isinstance(artifacts, list):
        return normalized_output

    normalized_artifacts: List[Any] = []
    for artifact in artifacts:
        if not isinstance(artifact, dict):
            normalized_artifacts.append(artifact)
            continue
        normalized_artifact = dict(artifact)
        normalized_artifact["doc_id"] = doc_id
        normalized_artifact["page_index"] = page_index
        anchors = artifact.get("source_anchors")
        if isinstance(anchors, list):
            normalized_artifact["source_anchors"] = [
                {**anchor, "page_index": page_index} if isinstance(anchor, dict) else anchor
                for anchor in anchors
            ]
        normalized_artifacts.append(normalized_artifact)
    normalized_output["artifacts"] = normalized_artifacts
    return normalized_output


def _generate_page_artifacts_with_optional_page_input(
    client: ArtifactCompilerClient,
    system_prompt: str,
    user_prompt: str,
    schema_dict: Dict[str, Any],
    page_input: Dict[str, Any],
) -> Dict[str, Any]:
    generate_page_artifacts = client.generate_page_artifacts
    if _callable_accepts_keyword(generate_page_artifacts, "page_input"):
        return generate_page_artifacts(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            schema_dict=schema_dict,
            page_input=page_input,
        )
    return generate_page_artifacts(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        schema_dict=schema_dict,
    )


def _callable_accepts_keyword(callable_obj: Any, keyword: str) -> bool:
    try:
        parameters = inspect.signature(callable_obj).parameters.values()
    except (TypeError, ValueError):
        return False
    return any(
        parameter.kind == inspect.Parameter.VAR_KEYWORD or parameter.name == keyword
        for parameter in parameters
    )


def compile_pages_with_client(
    canonical_record: Dict[str, Any],
    prepared_pages: List[Dict[str, Any]],
    client: ArtifactCompilerClient,
    schema_dict: Dict[str, Any],
    compiler_metadata: Dict[str, Any],
    raw_output_log_path: str | Path | None = None,
    discard_log_path: str | Path | None = None,
    compiler_version: str = "stage2_compiler_v1",
    prompt_version: str = "artifact_compiler_prompt_v1",
    deterministic_dedup_enabled: bool = True,
) -> Dict[str, Any]:
    """Compile prepared pages with a client without retry or repair."""

    page_results: Dict[int, Dict[str, Any]] = {}
    for page_input in prepared_pages:
        page_index = int(page_input["page_index"])
        page_results[page_index] = compile_page_with_client(
            canonical_record=canonical_record,
            page_input=page_input,
            client=client,
            schema_dict=schema_dict,
            compiler_metadata=compiler_metadata,
            raw_output_log_path=raw_output_log_path,
            discard_log_path=discard_log_path,
            compiler_version=compiler_version,
            prompt_version=prompt_version,
            deterministic_dedup_enabled=deterministic_dedup_enabled,
        )

    stats = [result["compilation_statistics"] for result in page_results.values()]
    num_raw_artifacts = sum(int(stat.get("num_raw_artifacts", 0)) for stat in stats)
    num_raw_artifacts_before_dedup = sum(
        int(stat.get("num_raw_artifacts_before_dedup", stat.get("num_raw_artifacts", 0)))
        for stat in stats
    )
    num_deduplicated_artifacts = sum(int(stat.get("num_deduplicated_artifacts", 0)) for stat in stats)
    num_valid_artifacts = sum(len(result["valid_artifacts"]) for result in page_results.values())
    num_validation_issues = sum(len(result["validation_issues"]) for result in page_results.values())

    return {
        "page_results": page_results,
        "summary": {
            "num_pages": len(prepared_pages),
            "deterministic_dedup_enabled": bool(deterministic_dedup_enabled),
            "dedup_stage": "after_raw_output_log_before_validation" if deterministic_dedup_enabled else None,
            "dedup_rule": (
                "doc_id+page_index+artifact_type+modality+source_anchor_ids+content_hash"
                if deterministic_dedup_enabled
                else None
            ),
            "num_raw_artifacts_before_dedup": num_raw_artifacts_before_dedup,
            "num_deduplicated_artifacts": num_deduplicated_artifacts,
            "deduplicated_artifact_issue_type_count": num_deduplicated_artifacts,
            "num_raw_artifacts": num_raw_artifacts,
            "num_valid_artifacts": num_valid_artifacts,
            "num_validation_issues": num_validation_issues,
            "schema_valid_rate_before_dedup": _rate(num_valid_artifacts, num_raw_artifacts_before_dedup),
            "schema_valid_rate_after_dedup": _rate(num_valid_artifacts, num_raw_artifacts),
            "discard_rate_before_dedup": _discard_rate(num_raw_artifacts_before_dedup, num_valid_artifacts),
            "discard_rate_after_dedup": _discard_rate(num_raw_artifacts, num_valid_artifacts),
        },
    }


def _count_raw_artifacts(raw_output: Any) -> int:
    if isinstance(raw_output, dict) and isinstance(raw_output.get("artifacts"), list):
        return len(raw_output["artifacts"])
    return 0


def _rate(numerator: int, denominator: int) -> float:
    return float(numerator) / float(max(1, denominator))


def _discard_rate(num_raw_artifacts: int, num_valid_artifacts: int) -> float:
    return max(0, num_raw_artifacts - num_valid_artifacts) / float(max(1, num_raw_artifacts))

# ---- from integration_dry_run.py ----


from pathlib import Path
from typing import Any, Dict, List

from .provider import build_mock_page_artifact_output
from .page_input import prepare_pages_for_compilation


FORBIDDEN_STORE_FIELDS = (
    "gold_annotation",
    "baseline_outputs",
    "source_record",
    "answer",
    "prediction",
    "final_answer",
    "evidence_pages",
    "evidence_sources",
    "binary_correctness",
    "proof_trace",
    "verified",
    "answer_supported",
    "proof_used",
)


def run_stage2_dry_run(
    canonical_record: Dict[str, Any],
    extract_path: str | Path,
    output_path: str | Path,
    compiler_metadata: Dict[str, Any] | None = None,
) -> Dict[str, Any]:
    """Run Stage 2 end to end with mock artifacts and deterministic validation."""

    prepared_result = prepare_pages_for_compilation(canonical_record, extract_path)
    prepared_pages = prepared_result["pages"]
    page_artifact_outputs: Dict[int, Dict[str, Any]] = {}
    validation_results: Dict[int, Dict[str, Any]] = {}
    all_validation_issues: List[Any] = []

    for page in prepared_pages:
        page_index = int(page["page_index"])
        raw_output = build_mock_page_artifact_output(
            doc_id=prepared_result["doc_id"],
            page_index=page_index,
            layout_blocks=page.get("layout_blocks", []),
        )
        valid_artifacts, validation_issues = validate_page_artifact_output(
            raw_output=raw_output,
            layout_blocks=page.get("layout_blocks", []),
        )
        page_artifact_outputs[page_index] = raw_output
        validation_results[page_index] = {
            "valid_artifacts": valid_artifacts,
            "validation_issues": [issue.to_dict() for issue in validation_issues],
        }
        all_validation_issues.extend(validation_issues)

    store = build_document_artifact_store(
        canonical_record=canonical_record,
        prepared_pages=prepared_pages,
        page_artifact_outputs=page_artifact_outputs,
        validation_results=validation_results,
        compiler_metadata=compiler_metadata or {},
    )
    write_artifact_store(store, output_path)
    quality_gate = _build_artifact_store_quality_gate(canonical_record, prepared_result, store)

    return {
        "artifact_store_path": str(output_path),
        "num_pages_prepared": len(prepared_pages),
        "num_pages_with_errors": len(prepared_result["errors"]),
        "num_valid_artifacts": sum(
            len(result.get("valid_artifacts", [])) for result in validation_results.values()
        ),
        "num_validation_issues": len(all_validation_issues),
        "quality_gate": quality_gate,
    }


def _build_artifact_store_quality_gate(
    canonical_record: Dict[str, Any],
    prepared_result: Dict[str, Any],
    store: Dict[str, Any],
) -> Dict[str, Any]:
    blocking_reasons: List[str] = []
    prepared_pages = prepared_result["pages"]
    candidate_pool = canonical_record.get("candidate_pool", {})
    explicit_pages = set(candidate_pool.get("explicit_constraint_pages", []))
    artifact_index_by_page = store.get("artifact_index", {}).get("by_page_index", {})

    if not prepared_pages:
        blocking_reasons.append("no_prepared_pages")
    if prepared_result.get("errors"):
        blocking_reasons.append("missing_source_anchors")
    if any(not page.get("layout_blocks") for page in prepared_pages):
        blocking_reasons.append("missing_required_page_layout_blocks")

    for explicit_page in explicit_pages:
        if int(explicit_page) == 29 and "29" not in artifact_index_by_page:
            blocking_reasons.append("missing_required_page_artifacts")

    if store.get("compilation_statistics", {}).get("num_artifacts", 0) == 0:
        blocking_reasons.append("no_valid_artifacts")
    if _contains_forbidden_field(store):
        blocking_reasons.append("forbidden_fields_present")

    return {
        "stage2_dry_run_passed": not blocking_reasons,
        "blocking_reasons": sorted(set(blocking_reasons)),
    }


def _contains_forbidden_field(value: Any) -> bool:
    if isinstance(value, dict):
        for key, child in value.items():
            if key in FORBIDDEN_STORE_FIELDS:
                return True
            if _contains_forbidden_field(child):
                return True
    elif isinstance(value, list):
        return any(_contains_forbidden_field(item) for item in value)
    return False

# ---- from compiler_integration.py ----


from pathlib import Path
from typing import Any, Dict

from .provider import ApiRunConfig, assert_real_api_allowed
from .provider import ArtifactCompilerClient, FakeArtifactCompilerClient, RealArtifactCompilerClient
from .page_input import prepare_pages_for_compilation
from .provider import ProviderError
from .logs import build_raw_output_log_entry, write_raw_output_log
from .provider import RealApiArtifactCompilerClient
from .artifact_schema import build_page_artifact_output_schema_dict


FORBIDDEN_OUTPUT_FIELDS = (
    "gold_annotation",
    "baseline_outputs",
    "source_record",
    "answer",
    "prediction",
    "final_answer",
    "evidence_pages",
    "evidence_sources",
    "binary_correctness",
    "proof_trace",
    "verified",
    "answer_supported",
    "proof_used",
)


def run_stage2_compiler_dry_run(
    canonical_record: Dict[str, Any],
    extract_path: str | Path,
    output_path: str | Path,
    client: ArtifactCompilerClient | None = None,
    enable_real_api: bool = False,
) -> Dict[str, Any]:
    """Run controlled Stage 2 compiler flow with fake client by default."""

    active_client = client or FakeArtifactCompilerClient()
    if isinstance(active_client, RealArtifactCompilerClient) and not enable_real_api:
        active_client.enable_real_api = False

    compiler_metadata = _build_compiler_metadata(active_client, enable_real_api)
    prepared_result = prepare_pages_for_compilation(canonical_record, extract_path)
    schema_dict = build_page_artifact_output_schema_dict()
    compile_result = compile_pages_with_client(
        canonical_record=canonical_record,
        prepared_pages=prepared_result["pages"],
        client=active_client,
        schema_dict=schema_dict,
        compiler_metadata=compiler_metadata,
    )

    page_artifact_outputs = {
        page_index: result["raw_output"]
        for page_index, result in compile_result["page_results"].items()
    }
    validation_results = {
        page_index: {
            "valid_artifacts": result["valid_artifacts"],
            "validation_issues": result["validation_issues"],
        }
        for page_index, result in compile_result["page_results"].items()
    }
    store = build_document_artifact_store(
        canonical_record=canonical_record,
        prepared_pages=prepared_result["pages"],
        page_artifact_outputs=page_artifact_outputs,
        validation_results=validation_results,
        compiler_metadata=compiler_metadata,
    )
    write_artifact_store(store, output_path)

    return {
        "artifact_store_path": str(output_path),
        "num_pages_prepared": len(prepared_result["pages"]),
        "num_pages_with_errors": len(prepared_result["errors"]),
        "num_valid_artifacts": compile_result["summary"]["num_valid_artifacts"],
        "num_validation_issues": compile_result["summary"]["num_validation_issues"],
        "quality_gate": _build_quality_gate(prepared_result, store),
    }


def run_stage2_single_page_real_api_smoke_test(
    canonical_record: Dict[str, Any],
    extract_path: str | Path,
    output_path: str | Path,
    api_config: ApiRunConfig,
    target_page_index: int | None = None,
    run_real_trial: bool = False,
) -> Dict[str, Any]:
    """Run one guarded real-provider smoke-test page through validation and store writing."""

    if not run_real_trial:
        raise RuntimeError("Real provider trial requires run_real_trial=True.")
    assert_real_api_allowed(api_config)
    prepared_result = prepare_pages_for_compilation(canonical_record, extract_path)
    selected_page_index = _select_target_page_index(canonical_record, target_page_index)
    selected_pages = [
        page for page in prepared_result["pages"] if int(page["page_index"]) == selected_page_index
    ][:1]

    raw_output_log_path = _default_log_path(
        api_config.raw_output_dir,
        output_path,
        f"raw_outputs_p{selected_page_index:03d}.jsonl",
    )
    discard_log_path = _default_log_path(
        api_config.discard_log_dir,
        output_path,
        f"discard_p{selected_page_index:03d}.jsonl",
    )
    compiler_metadata = _real_api_compiler_metadata(api_config)

    schema_dict = build_page_artifact_output_schema_dict()
    client = RealApiArtifactCompilerClient(api_config)
    try:
        compile_result = compile_pages_with_client(
            canonical_record=canonical_record,
            prepared_pages=selected_pages,
            client=client,
            schema_dict=schema_dict,
            compiler_metadata=compiler_metadata,
            raw_output_log_path=raw_output_log_path,
            discard_log_path=discard_log_path,
            compiler_version="stage2_compiler_v1",
            prompt_version="artifact_compiler_prompt_v1",
        )
        provider_error = None
    except Exception as exc:
        if not isinstance(exc, (ProviderError, NotImplementedError, RuntimeError)):
            raise
        compile_result = {"page_results": {}, "summary": {"num_valid_artifacts": 0, "num_validation_issues": 0}}
        provider_error = exc
        if selected_pages:
            _write_provider_error_raw_log(
                raw_output_log_path=raw_output_log_path,
                page_input=selected_pages[0],
                api_config=api_config,
                provider_error=exc,
            )

    page_artifact_outputs = {
        page_index: result["raw_output"]
        for page_index, result in compile_result["page_results"].items()
    }
    validation_results = {
        page_index: {
            "valid_artifacts": result["valid_artifacts"],
            "validation_issues": result["validation_issues"],
        }
        for page_index, result in compile_result["page_results"].items()
    }
    store = build_document_artifact_store(
        canonical_record=canonical_record,
        prepared_pages=selected_pages,
        page_artifact_outputs=page_artifact_outputs,
        validation_results=validation_results,
        compiler_metadata=compiler_metadata,
    )
    write_artifact_store(store, output_path)
    quality_gate = _build_single_page_quality_gate(selected_pages, compile_result, store, provider_error)

    return {
        "artifact_store_path": str(output_path),
        "target_page_index": selected_page_index,
        "num_pages_compiled": len(selected_pages),
        "num_raw_artifacts": sum(
            result["compilation_statistics"]["num_raw_artifacts"]
            for result in compile_result["page_results"].values()
        ),
        "num_valid_artifacts": compile_result["summary"]["num_valid_artifacts"],
        "num_validation_issues": compile_result["summary"]["num_validation_issues"],
        "raw_output_log_path": str(raw_output_log_path),
        "discard_log_path": str(discard_log_path),
        "quality_gate": quality_gate,
    }


def _build_compiler_metadata(
    client: ArtifactCompilerClient,
    enable_real_api: bool,
) -> Dict[str, Any]:
    if isinstance(client, FakeArtifactCompilerClient):
        return {
            "compiler_name": "fake_artifact_compiler_client",
            "compiler_version": "stage2_step5_fake",
            "schema_version": "stage2_artifact_schema_v1",
            "model_name": "mock",
            "temperature": None,
            "max_repair_attempts": 0,
        }
    return {
        "compiler_name": "real_artifact_compiler_client",
        "compiler_version": "stage2_step5_interface_only",
        "schema_version": "stage2_artifact_schema_v1",
        "model_name": "real_api_enabled" if enable_real_api else "real_api_disabled",
        "temperature": None,
        "max_repair_attempts": 0,
    }


def _real_api_compiler_metadata(api_config: ApiRunConfig) -> Dict[str, Any]:
    return {
        "compiler_name": "real_api_artifact_compiler_client",
        "compiler_version": "stage2_step7_real_provider_adapter",
        "schema_version": "stage2_artifact_schema_v1",
        "provider": api_config.provider,
        "model_name": api_config.model_name,
        "temperature": api_config.temperature,
        "max_repair_attempts": 0,
    }


def _build_quality_gate(
    prepared_result: Dict[str, Any],
    store: Dict[str, Any],
) -> Dict[str, Any]:
    blocking_reasons = []
    if not prepared_result["pages"]:
        blocking_reasons.append("no_prepared_pages")
    if prepared_result["errors"]:
        blocking_reasons.append("missing_source_anchors")
    if store.get("compilation_statistics", {}).get("num_artifacts", 0) == 0:
        blocking_reasons.append("no_valid_artifacts")
    if _contains_forbidden_output(store):
        blocking_reasons.append("forbidden_fields_present")
    return {
        "stage2_compiler_dry_run_passed": not blocking_reasons,
        "blocking_reasons": sorted(set(blocking_reasons)),
    }


def _build_single_page_quality_gate(
    selected_pages: list[Dict[str, Any]],
    compile_result: Dict[str, Any],
    store: Dict[str, Any],
    provider_error: Exception | None = None,
) -> Dict[str, Any]:
    blocking_reasons = []
    if provider_error is not None:
        blocking_reasons.append("provider_error")
    if len(selected_pages) != 1:
        blocking_reasons.append("single_page_selection_failed")
    if selected_pages and not selected_pages[0].get("layout_blocks"):
        blocking_reasons.append("missing_source_anchors")
    raw_outputs = [result.get("raw_output") for result in compile_result["page_results"].values()]
    if any(not isinstance(raw_output, dict) for raw_output in raw_outputs):
        blocking_reasons.append("invalid_raw_output_container")
    if compile_result["summary"]["num_valid_artifacts"] == 0:
        blocking_reasons.append("no_valid_artifacts")
    if _contains_forbidden_output(store):
        blocking_reasons.append("forbidden_fields_present")
    return {
        "single_page_smoke_test_passed": not blocking_reasons,
        "blocking_reasons": sorted(set(blocking_reasons)),
    }


def _write_provider_error_raw_log(
    raw_output_log_path: Path,
    page_input: Dict[str, Any],
    api_config: ApiRunConfig,
    provider_error: Exception,
) -> None:
    raw_text = getattr(provider_error, "raw_text", None)
    raw_output = {
        "provider_error": {
            "type": type(provider_error).__name__,
            "message": str(provider_error),
        }
    }
    write_raw_output_log(
        raw_output_log_path,
        build_raw_output_log_entry(
            doc_id=page_input["doc_id"],
            page_index=int(page_input["page_index"]),
            provider=api_config.provider,
            model_name=api_config.model_name,
            compiler_version="stage2_compiler_v1",
            prompt_version="artifact_compiler_prompt_v1",
            raw_output=raw_output,
            raw_text=raw_text,
            provider_error_type=type(provider_error).__name__,
            provider_error_message=str(provider_error),
        ),
    )


def _contains_forbidden_output(value: Any) -> bool:
    if isinstance(value, dict):
        for key, child in value.items():
            if key in FORBIDDEN_OUTPUT_FIELDS:
                return True
            if _contains_forbidden_output(child):
                return True
    elif isinstance(value, list):
        return any(_contains_forbidden_output(item) for item in value)
    return False


def _select_target_page_index(
    canonical_record: Dict[str, Any],
    target_page_index: int | None,
) -> int:
    if target_page_index is not None:
        return int(target_page_index)
    explicit_pages = canonical_record.get("candidate_pool", {}).get("explicit_constraint_pages", [])
    if explicit_pages:
        return int(explicit_pages[0])
    return int(canonical_record["compilation_plan"]["pages_to_compile"][0])


def _default_log_path(
    configured_dir: str | Path | None,
    output_path: str | Path,
    file_name: str,
) -> Path:
    if configured_dir is not None:
        return Path(configured_dir) / file_name
    return Path(output_path).parent / file_name
