"""Consolidated Stage 2 module.

Generated by module consolidation; public behavior is preserved.
"""

from __future__ import annotations


# ---- from field_aliases.py ----


import re
from typing import Any, Mapping, Optional, Sequence


SOURCE_FIELD_ALIASES: Mapping[str, Sequence[str]] = {
    "doc_id": ("doc_id",),
    "doc_type": ("doc_type",),
    "question_text": ("question",),
    "answer_format": ("answer_format",),
    "answer": ("answer",),
    "evidence_pages": ("evidence_pages",),
    "evidence_sources": ("evidence_sources",),
    "mdocagent_retrieval_query": ("retrieval-query",),
    "mdocagent_retrieval_key": ("retrieval-key",),
    "qwen_retrieval_query": ("qwen_retrieval-query",),
    "qwen_retrieval_key": ("qwen_retrieval-key",),
    "text_index_path": ("text-index-path-question",),
    "text_ranked_pages": ("text-top-10-question",),
    "text_ranked_scores": ("text-top-10-question_score",),
    "image_ranked_pages": ("image-top-10-question",),
    "image_ranked_scores": ("image-top-10-question_score",),
    "mdocagent_answer": ("ans_mmlb-MDocAgent",),
    "binary_correctness": ("binary_correctness",),
}


PATTERN_FIELD_ALIASES: Mapping[str, Sequence[re.Pattern[str]]] = {
    "text_ranked_pages": (re.compile(r"^text-top-\d+-question$"),),
    "text_ranked_scores": (re.compile(r"^text-top-\d+-question_score$"),),
    "image_ranked_pages": (re.compile(r"^image-top-\d+-question$"),),
    "image_ranked_scores": (re.compile(r"^image-top-\d+-question_score$"),),
    "text_index_path": (re.compile(r"^text-index-path-question$"),),
}


COMPILER_EXCLUDED_FIELDS: Sequence[str] = (
    "source_record",
    "gold_annotation",
    "baseline_outputs",
)


def get_source_value(
    source_record: Mapping[str, Any],
    field_key: str,
    default: Any = None,
) -> Any:
    """Return a source value using approved aliases for a normalized field key."""

    for source_field_name in SOURCE_FIELD_ALIASES.get(field_key, ()):
        if source_field_name in source_record:
            return source_record[source_field_name]

    pattern_match = find_pattern_field_name(source_record, field_key)
    if pattern_match is not None:
        return source_record[pattern_match]

    return default


def require_source_value(source_record: Mapping[str, Any], field_key: str) -> Any:
    """Return a required source value or raise a field-specific ValueError."""

    value = get_source_value(source_record, field_key, default=None)
    if value is None:
        raise ValueError(f"Missing required source field for {field_key!r}")
    return value


def find_pattern_field_name(
    source_record: Mapping[str, Any],
    field_key: str,
) -> Optional[str]:
    """Find a dynamically named retrieval field such as top-4 or top-20."""

    patterns = PATTERN_FIELD_ALIASES.get(field_key, ())
    if not patterns:
        return None
    matches = [
        source_field_name
        for source_field_name in source_record.keys()
        if any(pattern.match(source_field_name) for pattern in patterns)
    ]
    if not matches:
        return None

    def _top_k_sort_key(source_field_name: str) -> tuple[int, str]:
        match = re.search(r"-top-(\d+)-", source_field_name)
        top_k = int(match.group(1)) if match else -1
        return (-top_k, source_field_name)

    return sorted(matches, key=_top_k_sort_key)[0]

# ---- from retrieval_processor.py ----


import ast
from typing import Any, Dict, List, Optional, Sequence


def parse_sequence_field(value: Any, field_name: str) -> List[Any]:
    """Parse a source field that may be a list or a stringified Python list."""

    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return []
        parsed = ast.literal_eval(stripped)
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, tuple):
            return list(parsed)
    raise ValueError(f"Cannot parse list field {field_name!r}: {value!r}")


def deduplicate_ranked_pages(
    pages: Sequence[Any],
    scores: Sequence[Any],
) -> List[Dict[str, Any]]:
    """Deduplicate ranked page indices while retaining first rank and duplicates."""

    seen: Dict[int, Dict[str, Any]] = {}

    for index, raw_page in enumerate(pages):
        page_index = _coerce_page_index(raw_page)
        rank = index + 1
        score = _coerce_score(scores[index]) if index < len(scores) else None

        if page_index not in seen:
            seen[page_index] = {
                "page_index": page_index,
                "rank": rank,
                "score": score,
                "duplicate_ranks": [rank],
            }
        else:
            seen[page_index]["duplicate_ranks"].append(rank)

    ranked_pages_unique: List[Dict[str, Any]] = []
    for item in seen.values():
        if len(item["duplicate_ranks"]) == 1:
            item.pop("duplicate_ranks")
        ranked_pages_unique.append(item)

    return sorted(ranked_pages_unique, key=lambda item: item["rank"])


def _coerce_page_index(value: Any) -> int:
    if isinstance(value, bool):
        raise ValueError(f"Invalid boolean page index: {value!r}")
    page_index = int(value)
    if page_index < 0:
        raise ValueError(f"Invalid negative page index: {value!r}")
    return page_index


def _coerce_score(value: Any) -> Optional[float]:
    if value is None:
        return None
    return float(value)

# ---- from constraint_parser.py ----


import re
from typing import Any, Dict, List


PAGE_PATTERN = re.compile(r"\bpages?\s+(\d+)\b", re.IGNORECASE)
COLOR_TERMS = ("blue", "red", "black", "green", "yellow", "white")


def extract_explicit_page_references(question_text: str) -> List[Dict[str, Any]]:
    """Extract explicit one-based page references from the question text."""

    references: List[Dict[str, Any]] = []
    for match in PAGE_PATTERN.finditer(question_text or ""):
        page_number = int(match.group(1))
        if page_number < 1:
            continue

        references.append(
            {
                "surface_text": match.group(0),
                "page_number_one_based": page_number,
                "page_index_zero_based": page_number - 1,
                "source": "question_text",
            }
        )
    return references


def extract_visual_attribute_constraints(question_text: str) -> List[Dict[str, str]]:
    """Extract simple visual attributes that should bias compilation."""

    q = (question_text or "").lower()
    constraints: List[Dict[str, str]] = []

    for color in COLOR_TERMS:
        if re.search(rf"\b{re.escape(color)}\b", q):
            constraints.append(
                {
                    "attribute_type": "color",
                    "attribute_value": color,
                    "source": "question_text",
                }
            )

    if re.search(r"\b(handwritten|handwriting)\b", q):
        constraints.append(
            {
                "attribute_type": "script_type",
                "attribute_value": "handwritten",
                "source": "question_text",
            }
        )

    return constraints


def infer_target_object(question_text: str) -> Dict[str, str]:
    """Infer a coarse target object and modality requirement from the question."""

    q = (question_text or "").lower()

    if re.search(r"\bwords?\b", q):
        object_type = "words"
    elif re.search(r"\bsignature\b", q):
        object_type = "signature"
    elif re.search(r"\bstamp\b", q):
        object_type = "stamp"
    else:
        object_type = "unspecified"

    visual_terms = (
        "color",
        "blue",
        "red",
        "black",
        "green",
        "yellow",
        "white",
        "handwritten",
        "handwriting",
        "image",
        "figure",
        "page",
    )
    modality_requirement = "visual" if any(term in q for term in visual_terms) else "text"

    return {
        "object_type": object_type,
        "modality_requirement": modality_requirement,
    }


def parse_question_constraints(question_text: str) -> Dict[str, Any]:
    """Build the approved question_constraints block for canonical records."""

    return {
        "explicit_page_references": extract_explicit_page_references(question_text),
        "visual_attribute_constraints": extract_visual_attribute_constraints(question_text),
        "target_object": infer_target_object(question_text),
    }

# ---- from mdocagent_compat.py ----


import ast
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from .provider import ApiRunConfig


def normalize_doc_name_for_mdocagent(doc_id: str) -> str:
    """Return the MDocAgent extracted page stem by removing only a .pdf suffix."""

    return doc_id[:-4] if doc_id.endswith(".pdf") else doc_id


def build_mdocagent_extract_paths(
    extract_root: str | Path,
    doc_id: str,
    page_index: int,
) -> Dict[str, Any]:
    """Build original MDocAgent page paths first, followed by legacy fallbacks."""

    root = Path(extract_root)
    page_index = int(page_index)
    doc_name = normalize_doc_name_for_mdocagent(doc_id)
    text_candidates = [
        root / f"{doc_name}_{page_index}.txt",
        root / f"{doc_name}_{page_index:03d}.txt",
        root / "texts" / f"{doc_name}_{page_index}.txt",
        root / "texts" / f"{doc_name}_{page_index:03d}.txt",
        root / "texts" / f"page_{page_index}.txt",
        root / "texts" / f"page_{page_index:03d}.txt",
    ]
    image_candidates = [
        root / f"{doc_name}_{page_index}.png",
        root / f"{doc_name}_{page_index:03d}.png",
        root / "images" / f"{doc_name}_{page_index}.png",
        root / "images" / f"{doc_name}_{page_index:03d}.png",
        root / "images" / f"page_{page_index}.png",
        root / "images" / f"page_{page_index:03d}.png",
    ]
    return {
        "doc_name": doc_name,
        "text_path": text_candidates[0],
        "image_path": image_candidates[0],
        "text_candidate_paths": text_candidates,
        "image_candidate_paths": image_candidates,
    }


def load_mdocagent_model_config(config_path: str | Path) -> Dict[str, Any]:
    """Load a MDocAgent model yaml without printing or logging secrets."""

    path = Path(config_path)
    data = _load_yaml_mapping(path)
    allowed_fields = {
        "model_id",
        "model",
        "model_name",
        "base_url",
        "api_base_url",
        "api_key",
        "api_key_env",
        "api_key_env_var",
        "module_name",
        "class_name",
        "temperature",
        "max_tokens",
        "max_new_tokens",
    }
    return {key: value for key, value in data.items() if key in allowed_fields}


def build_api_run_config_from_mdocagent_yaml(
    config_path: str | Path,
    overrides: Optional[Dict[str, Any]] = None,
) -> ApiRunConfig:
    """Map MDocAgent model yaml fields to ApiRunConfig with max_pages fixed to 1."""

    overrides = dict(overrides or {})
    if "max_pages" in overrides and int(overrides["max_pages"]) != 1:
        raise RuntimeError("Stage 2 real API trials require max_pages=1.")

    yaml_config = load_mdocagent_model_config(config_path)
    model_name = yaml_config.get("model") or yaml_config.get("model_name") or yaml_config.get("model_id")
    max_tokens = yaml_config.get("max_tokens", yaml_config.get("max_new_tokens"))
    return ApiRunConfig(
        enable_real_api=bool(overrides.get("enable_real_api", False)),
        provider=str(overrides.get("provider", "siliconflow")),
        model_name=overrides.get("model_name", model_name),
        max_pages=1,
        temperature=float(overrides.get("temperature", yaml_config.get("temperature", 0.0) or 0.0)),
        timeout_seconds=int(overrides.get("timeout_seconds", 120)),
        raw_output_dir=overrides.get("raw_output_dir"),
        discard_log_dir=overrides.get("discard_log_dir"),
        api_base_url=overrides.get("api_base_url", yaml_config.get("api_base_url") or yaml_config.get("base_url")),
        api_key_env_var=str(
            overrides.get(
                "api_key_env_var",
                yaml_config.get("api_key_env_var") or yaml_config.get("api_key_env") or "SILICONFLOW_API_KEY",
            )
        ),
        api_key=overrides.get("api_key", yaml_config.get("api_key")),
        max_tokens=int(max_tokens) if max_tokens not in (None, "") else None,
    )


def read_json_or_jsonl_records(path: str | Path) -> List[Dict[str, Any]]:
    """Read either a JSON list file or a JSONL file into a list of records."""

    file_path = Path(path)
    text = file_path.read_text(encoding="utf-8")
    stripped = text.strip()
    if not stripped:
        return []
    if stripped[0] in "[{":
        parsed = json.loads(stripped)
        if isinstance(parsed, list):
            return [record for record in parsed if isinstance(record, dict)]
        if isinstance(parsed, dict):
            return [parsed]
        raise ValueError(f"Unsupported JSON root type: {type(parsed).__name__}")

    records: List[Dict[str, Any]] = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        if not line.strip():
            continue
        record = json.loads(line)
        if not isinstance(record, dict):
            raise ValueError(f"JSONL line {line_number} is not an object.")
        records.append(record)
    return records


def find_record_by_id_or_doc_question(
    records: List[Dict[str, Any]],
    record_id: Optional[str],
    doc_id: Optional[str],
    question_substring: Optional[str],
) -> Dict[str, Any]:
    """Locate one normalized or raw MDocAgent record without exposing eval-only fields."""

    if record_id:
        for record in records:
            if record.get("record_id") == record_id:
                return record

    normalized_question = (question_substring or "").lower()
    for record in records:
        candidate = record.get("canonical_record", record)
        document = candidate.get("document", {}) if isinstance(candidate, dict) else {}
        raw_question = candidate.get("question", {}) if isinstance(candidate, dict) else {}
        candidate_doc_id = document.get("doc_id") or record.get("doc_id")
        if isinstance(raw_question, dict):
            candidate_question = raw_question.get("text") or record.get("question") or record.get("question_text") or ""
        else:
            candidate_question = raw_question or record.get("question") or record.get("question_text") or ""
        if doc_id and candidate_doc_id != doc_id:
            continue
        if normalized_question and normalized_question not in str(candidate_question).lower():
            continue
        return record

    raise ValueError("No matching record found for the requested identifiers.")


def summarize_mdocagent_model_config(config_path: str | Path, api_config: ApiRunConfig) -> Dict[str, Any]:
    """Build a secret-free config summary for preflight reports."""

    yaml_config = load_mdocagent_model_config(config_path)
    return {
        "provider": api_config.provider,
        "model_name": api_config.model_name,
        "api_base_url_present": bool(api_config.api_base_url),
        "api_key_env_var": api_config.api_key_env_var,
        "api_key_present_in_yaml": bool(yaml_config.get("api_key")),
    }


def _load_yaml_mapping(path: Path) -> Dict[str, Any]:
    try:
        import yaml  # type: ignore
    except ImportError:
        return _load_simple_yaml_mapping(path)

    loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(loaded, dict):
        raise ValueError(f"YAML root must be a mapping: {path}")
    return dict(loaded)


def _load_simple_yaml_mapping(path: Path) -> Dict[str, Any]:
    result: Dict[str, Any] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].rstrip()
        if not line.strip() or line.lstrip().startswith("-") or line.startswith(" "):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value == "":
            continue
        result[key] = _parse_scalar(value)
    return result


def _parse_scalar(value: str) -> Any:
    lowered = value.lower()
    if lowered in {"null", "none", "~"}:
        return None
    if lowered in {"true", "false"}:
        return lowered == "true"
    try:
        return ast.literal_eval(value)
    except Exception:
        return value.strip().strip('"').strip("'")

# ---- from page_range_validation.py ----


import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Set



PAGE_RANGE_POLICY = "retrieval_union_plus_valid_explicit_page_constraints"
OUT_OF_RANGE_ERROR = "explicit_page_reference_out_of_range"
PAGE_COUNT_UNKNOWN_ERROR = "document_page_count_unknown"


def infer_document_page_count(
    doc_id: str,
    pdf_root: str | Path | None = None,
    extract_root: str | Path | None = None,
) -> Dict[str, Any]:
    """Infer document page count from a PDF first, then extracted page files."""

    pdf_path = _find_pdf_path(doc_id, pdf_root)
    if pdf_path is not None:
        page_count = _read_pdf_page_count(pdf_path)
        if page_count is not None:
            return {
                "page_count": page_count,
                "source": "pdf",
                "available_page_indices": list(range(page_count)),
                "page_index_contiguous": True,
            }

    available_page_indices = _find_extract_page_indices(doc_id, extract_root)
    if available_page_indices:
        page_count = max(available_page_indices) + 1
        return {
            "page_count": page_count,
            "source": "extract_files",
            "available_page_indices": available_page_indices,
            "page_index_contiguous": available_page_indices == list(range(page_count)),
        }

    return {
        "page_count": None,
        "source": "unknown",
        "available_page_indices": [],
        "page_index_contiguous": None,
    }


def validate_explicit_page_references_against_page_count(
    canonical_record: Dict[str, Any],
    page_count_info: Dict[str, Any],
) -> Dict[str, Any]:
    """Validate all explicit page references against known document bounds."""

    explicit_refs = canonical_record.get("question_constraints", {}).get("explicit_page_references", [])
    page_count = page_count_info.get("page_count")
    available_indices = sorted({int(index) for index in page_count_info.get("available_page_indices", [])})
    valid_indices: Set[int] = set()
    invalid_refs: List[Dict[str, Any]] = []

    for raw_ref in explicit_refs:
        ref = _normalize_explicit_ref(raw_ref)
        page_index = ref["page_index_zero_based"]
        if page_count is not None:
            if 0 <= page_index < int(page_count):
                valid_indices.add(page_index)
            else:
                invalid_refs.append(_build_out_of_range_ref(ref, int(page_count), page_count_info))
        elif available_indices:
            if page_index in available_indices:
                valid_indices.add(page_index)
            else:
                invalid_refs.append(_build_out_of_range_ref(ref, None, page_count_info))
        else:
            unknown_ref = dict(ref)
            unknown_ref.update(
                {
                    "error_type": PAGE_COUNT_UNKNOWN_ERROR,
                    "page_count": None,
                    "max_valid_page_index": None,
                }
            )
            invalid_refs.append(unknown_ref)

    return {
        "valid_explicit_page_indices": sorted(valid_indices),
        "invalid_explicit_page_references": invalid_refs,
        "page_count_info": page_count_info,
    }


def apply_explicit_page_range_validation_to_canonical_record(
    canonical_record: Dict[str, Any],
    page_count_info: Dict[str, Any],
) -> Dict[str, Any]:
    """Update candidate_pool and compilation_plan with only valid explicit pages."""

    validation = validate_explicit_page_references_against_page_count(canonical_record, page_count_info)
    candidate_pool = canonical_record.setdefault("candidate_pool", {})
    raw_explicit_pages = _extract_raw_explicit_page_indices(canonical_record)
    valid_explicit_pages = validation["valid_explicit_page_indices"]
    invalid_explicit_refs = validation["invalid_explicit_page_references"]
    invalid_explicit_pages = {
        int(ref["page_index_zero_based"])
        for ref in invalid_explicit_refs
        if ref.get("page_index_zero_based") is not None
    }
    retrieval_pages = _coerce_page_list(candidate_pool.get("retrieval_candidate_pages", []))
    required_pages = sorted((set(retrieval_pages) | set(valid_explicit_pages)) - invalid_explicit_pages)

    candidate_pool.update(
        {
            "retrieval_candidate_pages": retrieval_pages,
            "explicit_constraint_pages_raw": raw_explicit_pages,
            "explicit_constraint_pages_valid": valid_explicit_pages,
            "explicit_constraint_pages_invalid": invalid_explicit_refs,
            "explicit_constraint_pages": valid_explicit_pages,
            "required_pages_for_compilation": required_pages,
            "retrieval_missed_explicit_pages": [
                page for page in valid_explicit_pages if page not in retrieval_pages
            ],
            "candidate_pool_policy": PAGE_RANGE_POLICY,
            "explicit_page_range_validation": validation,
        }
    )

    compilation_plan = canonical_record.setdefault("compilation_plan", {})
    compilation_plan.update(
        {
            "compile_scope": PAGE_RANGE_POLICY,
            "pages_to_compile": required_pages,
            "priority_pages": valid_explicit_pages,
            "compilation_reasons": _build_valid_compilation_reasons(canonical_record, valid_explicit_pages),
        }
    )
    return validation


def _find_pdf_path(doc_id: str, pdf_root: str | Path | None) -> Optional[Path]:
    doc_path = Path(doc_id)
    doc_name = normalize_doc_name_for_mdocagent(doc_path.name)
    candidates: List[Path] = []
    if doc_path.is_file():
        candidates.append(doc_path)
    if pdf_root is not None:
        root = Path(pdf_root)
        candidates.extend(
            [
                root / doc_id,
                root / doc_path.name,
                root / f"{doc_name}.pdf",
            ]
        )
    for candidate in candidates:
        if candidate.is_file() and candidate.suffix.lower() == ".pdf":
            return candidate
    return None


def _read_pdf_page_count(pdf_path: Path) -> Optional[int]:
    for module_name in ("pypdf", "PyPDF2"):
        try:
            module = __import__(module_name)
            reader = module.PdfReader(str(pdf_path))
            return len(reader.pages)
        except Exception:
            continue
    try:
        import fitz  # type: ignore

        with fitz.open(str(pdf_path)) as document:
            return int(document.page_count)
    except Exception:
        return None


def _find_extract_page_indices(doc_id: str, extract_root: str | Path | None) -> List[int]:
    if extract_root is None:
        return []
    root = Path(extract_root)
    if not root.exists():
        return []
    doc_name = normalize_doc_name_for_mdocagent(Path(doc_id).name)
    pattern = re.compile(rf"^{re.escape(doc_name)}_(\d+)\.(?:png|txt)$", re.IGNORECASE)
    indices: Set[int] = set()
    for scan_root in (root, root / "texts", root / "images"):
        if not scan_root.is_dir():
            continue
        for path in scan_root.iterdir():
            if not path.is_file():
                continue
            match = pattern.match(path.name)
            if match:
                indices.add(int(match.group(1)))
    return sorted(indices)


def _normalize_explicit_ref(raw_ref: Dict[str, Any]) -> Dict[str, Any]:
    page_number = raw_ref.get("page_number_one_based")
    page_index = raw_ref.get("page_index_zero_based")
    if page_index is None and page_number is not None:
        page_index = int(page_number) - 1
    if page_number is None and page_index is not None:
        page_number = int(page_index) + 1
    page_index = int(page_index) if page_index is not None else -1
    page_number = int(page_number) if page_number is not None else page_index + 1
    return {
        "surface_text": raw_ref.get("surface_text", f"page {page_number}"),
        "page_number_one_based": page_number,
        "page_index_zero_based": page_index,
        "source": raw_ref.get("source", "question_text"),
    }


def _build_out_of_range_ref(
    ref: Dict[str, Any],
    page_count: Optional[int],
    page_count_info: Dict[str, Any],
) -> Dict[str, Any]:
    available_indices = page_count_info.get("available_page_indices", [])
    max_valid_page_index = page_count - 1 if page_count is not None else (max(available_indices) if available_indices else None)
    result = dict(ref)
    result.update(
        {
            "error_type": OUT_OF_RANGE_ERROR,
            "page_count": page_count,
            "max_valid_page_index": max_valid_page_index,
        }
    )
    return result


def _extract_raw_explicit_page_indices(canonical_record: Dict[str, Any]) -> List[int]:
    pages = []
    for ref in canonical_record.get("question_constraints", {}).get("explicit_page_references", []):
        page_index = _normalize_explicit_ref(ref)["page_index_zero_based"]
        if page_index >= 0:
            pages.append(page_index)
    return sorted(set(pages))


def _coerce_page_list(raw_pages: Any) -> List[int]:
    pages: Set[int] = set()
    for raw_page in raw_pages or []:
        if isinstance(raw_page, bool):
            continue
        page_index = int(raw_page)
        if page_index >= 0:
            pages.add(page_index)
    return sorted(pages)


def _build_valid_compilation_reasons(
    canonical_record: Dict[str, Any],
    valid_explicit_pages: List[int],
) -> List[Dict[str, Any]]:
    valid_set = set(valid_explicit_pages)
    reasons: List[Dict[str, Any]] = []
    for raw_ref in canonical_record.get("question_constraints", {}).get("explicit_page_references", []):
        ref = _normalize_explicit_ref(raw_ref)
        if ref["page_index_zero_based"] in valid_set:
            reasons.append(
                {
                    "page_index": ref["page_index_zero_based"],
                    "reason_type": "explicit_page_reference",
                    "reason_text": ref["surface_text"],
                }
            )
    return reasons

# ---- from candidate_pool_builder.py ----


from typing import Any, Dict, List


PAGE_RANGE_POLICY = "retrieval_union_plus_valid_explicit_page_constraints"


def build_candidate_pool(
    text_ranked_pages_unique: List[Dict[str, Any]],
    image_ranked_pages_unique: List[Dict[str, Any]],
    explicit_page_references: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Merge retrieval pages with explicit page constraints for compilation."""

    retrieval_pages = sorted(
        {item["page_index"] for item in text_ranked_pages_unique}
        | {item["page_index"] for item in image_ranked_pages_unique}
    )
    explicit_pages_raw = sorted(
        {
            item["page_index_zero_based"]
            for item in explicit_page_references
            if item["page_index_zero_based"] >= 0
        }
    )
    explicit_pages_valid = list(explicit_pages_raw)
    required_pages = sorted(set(retrieval_pages) | set(explicit_pages_valid))
    missed_explicit_pages = [page for page in explicit_pages_valid if page not in retrieval_pages]

    return {
        "retrieval_candidate_pages": retrieval_pages,
        "explicit_constraint_pages_raw": explicit_pages_raw,
        "explicit_constraint_pages_valid": explicit_pages_valid,
        "explicit_constraint_pages_invalid": [],
        "explicit_constraint_pages": explicit_pages_valid,
        "required_pages_for_compilation": required_pages,
        "retrieval_missed_explicit_pages": missed_explicit_pages,
        "candidate_pool_policy": PAGE_RANGE_POLICY,
    }

# ---- from normalize_record.py ----


import hashlib
import os
import re
from typing import Any, Dict, List, Mapping



def parse_list_field(value: Any) -> List[Any]:
    """Parse list-like source values for eval-only annotations."""

    return parse_sequence_field(value, field_name="list_field")


def make_record_id(doc_id: str, question: str) -> str:
    """Create a deterministic record id from document id and question text."""

    raw = f"{doc_id}::{question}"
    suffix = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:10]
    stem = os.path.basename(doc_id).removesuffix(".pdf")
    normalized_stem = re.sub(r"[^A-Za-z0-9_]+", "_", stem).strip("_") or "document"
    return f"{normalized_stem}__{suffix}"


def normalize_record(source_record: Mapping[str, Any]) -> Dict[str, Any]:
    """Normalize one raw retrieval record into the approved Stage 2 structure."""

    doc_id = str(require_source_value(source_record, "doc_id"))
    question_text = str(require_source_value(source_record, "question_text"))
    record_id = make_record_id(doc_id, question_text)

    evidence_pages_raw = parse_list_field(get_source_value(source_record, "evidence_pages", []))
    evidence_sources = parse_list_field(get_source_value(source_record, "evidence_sources", []))
    answer = get_source_value(source_record, "answer")

    text_pages = parse_sequence_field(
        get_source_value(source_record, "text_ranked_pages", []),
        field_name="text_ranked_pages",
    )
    text_scores = parse_sequence_field(
        get_source_value(source_record, "text_ranked_scores", []),
        field_name="text_ranked_scores",
    )
    image_pages = parse_sequence_field(
        get_source_value(source_record, "image_ranked_pages", []),
        field_name="image_ranked_pages",
    )
    image_scores = parse_sequence_field(
        get_source_value(source_record, "image_ranked_scores", []),
        field_name="image_ranked_scores",
    )

    text_unique = deduplicate_ranked_pages(text_pages, text_scores)
    image_unique = deduplicate_ranked_pages(image_pages, image_scores)
    question_constraints = parse_question_constraints(question_text)
    candidate_pool = build_candidate_pool(
        text_ranked_pages_unique=text_unique,
        image_ranked_pages_unique=image_unique,
        explicit_page_references=question_constraints["explicit_page_references"],
    )

    canonical_record = {
        "document": {
            "doc_id": doc_id,
            "doc_type": get_source_value(source_record, "doc_type"),
        },
        "question": {
            "text": question_text,
            "answer_format": get_source_value(source_record, "answer_format"),
        },
        "gold_annotation": {
            "answer": answer,
            "is_answerable": _infer_is_answerable(answer),
            "evidence_pages_raw": evidence_pages_raw,
            "evidence_pages_zero_based": _convert_one_based_pages_to_zero_based(evidence_pages_raw),
            "evidence_sources": evidence_sources,
            "eval_only": True,
        },
        "query_rewrites": {
            "mdocagent_retrieval_query": get_source_value(source_record, "mdocagent_retrieval_query"),
            "mdocagent_retrieval_key": get_source_value(source_record, "mdocagent_retrieval_key"),
            "qwen_retrieval_query": get_source_value(source_record, "qwen_retrieval_query"),
            "qwen_retrieval_key": get_source_value(source_record, "qwen_retrieval_key"),
        },
        "question_constraints": question_constraints,
        "retrieval": {
            "text": {
                "index_path": get_source_value(source_record, "text_index_path"),
                "ranked_pages_raw": text_pages,
                "ranked_scores_raw": text_scores,
                "ranked_pages_unique": text_unique,
            },
            "image": {
                "ranked_pages_raw": image_pages,
                "ranked_scores_raw": image_scores,
                "ranked_pages_unique": image_unique,
            },
        },
        "candidate_pool": candidate_pool,
        "compilation_plan": {
            "compile_scope": "retrieval_union_plus_explicit_page_constraints",
            "pages_to_compile": candidate_pool["required_pages_for_compilation"],
            "priority_pages": candidate_pool["explicit_constraint_pages"],
            "compilation_reasons": [
                {
                    "page_index": ref["page_index_zero_based"],
                    "reason_type": "explicit_page_reference",
                    "reason_text": ref["surface_text"],
                }
                for ref in question_constraints["explicit_page_references"]
            ],
            "excluded_fields_from_compiler": list(COMPILER_EXCLUDED_FIELDS),
        },
        "artifact_compilation": {
            "artifact_store_path": None,
            "validation_summary": None,
            "quality_gate": None,
        },
        "baseline_outputs": {
            "mdocagent": {
                "answer": get_source_value(source_record, "mdocagent_answer"),
                "binary_correctness": get_source_value(source_record, "binary_correctness"),
            },
            "eval_only": True,
        },
    }

    return {
        "record_id": record_id,
        "source_record": dict(source_record),
        "canonical_record": canonical_record,
    }


def _infer_is_answerable(answer: Any) -> bool:
    if answer is None:
        return False
    return str(answer).strip().lower() != "not answerable"


def _convert_one_based_pages_to_zero_based(evidence_pages_raw: List[Any]) -> List[int]:
    zero_based_pages: List[int] = []
    for raw_page in evidence_pages_raw:
        if isinstance(raw_page, bool):
            continue
        page_number = int(raw_page)
        if page_number >= 1:
            zero_based_pages.append(page_number - 1)
    return zero_based_pages

# ---- from mdocagent_aligned_stage2.py ----


import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional

from .page_input import build_basic_layout_blocks, find_existing_file


TEXT_TOP_10_FIELD = "text-top-10-question"
IMAGE_TOP_10_FIELD = "image-top-10-question"
FORBIDDEN_STAGE2_FIELDS = {
    "answer",
    "evidence_pages",
    "evidence_sources",
    "binary_correctness",
    "api_key",
    "proof_trace",
    "verified",
    "answer_supported",
    "proof_used",
}


SUMMARY_FORBIDDEN_FIELDS = FORBIDDEN_STAGE2_FIELDS | {
    "gold_annotation",
    "baseline_outputs",
}


def augment_retrieval_results_file(
    input_path: str | Path,
    output_path: str | Path,
    extract_root: str | Path,
    config_path: str | Path | None = None,
    max_records: int | None = None,
) -> List[Dict[str, Any]]:
    """Read MDocAgent retrieval results and write records with only a stage2 addition."""

    records = read_json_or_jsonl_records(input_path)
    augmented = augment_retrieval_records(
        records=records,
        extract_root=extract_root,
        config_path=config_path,
        max_records=max_records,
    )
    write_json(augmented, output_path)
    return augmented


def augment_retrieval_records(
    records: Iterable[Mapping[str, Any]],
    extract_root: str | Path,
    config_path: str | Path | None = None,
    max_records: int | None = None,
) -> List[Dict[str, Any]]:
    """Append a stage2 preflight block while preserving all original fields."""

    if config_path is not None and not Path(config_path).is_file():
        raise FileNotFoundError(f"Config path does not exist: {config_path}")

    result: List[Dict[str, Any]] = []
    for index, record in enumerate(records):
        if max_records is not None and index >= int(max_records):
            break
        augmented_record = dict(record)
        augmented_record["stage2"] = build_stage2_preflight(record, extract_root)
        result.append(augmented_record)
    return result


def build_stage2_preflight(record: Mapping[str, Any], extract_root: str | Path) -> Dict[str, Any]:
    """Build the compact Stage 2 page-route index for one retrieval result record."""

    doc_id = str(record["doc_id"])
    candidate_page_routes = build_candidate_page_routes(record)
    candidate_page_sources = [
        build_page_source(
            doc_id=doc_id,
            extract_root=extract_root,
            page_index=route["page_index"],
        )
        for route in candidate_page_routes
    ]
    blocking_reasons = build_preflight_blocking_reasons(
        candidate_page_routes=candidate_page_routes,
        candidate_page_sources=candidate_page_sources,
    )

    return {
        "preflight": {
            "passed": not blocking_reasons,
            "blocking_reasons": blocking_reasons,
        },
        "candidate_page_routes": candidate_page_routes,
    }


def build_candidate_page_routes(record: Mapping[str, Any]) -> List[Dict[str, Any]]:
    """Build compact page routes from original MDocAgent text/image top-10 fields."""

    text_pages_raw = parse_sequence_field(record.get(TEXT_TOP_10_FIELD, []), TEXT_TOP_10_FIELD)
    image_pages_raw = parse_sequence_field(record.get(IMAGE_TOP_10_FIELD, []), IMAGE_TOP_10_FIELD)
    route_map: Dict[int, set[str]] = {}
    for page_index in text_pages_raw:
        route_map.setdefault(int(page_index), set()).add("text")
    for page_index in image_pages_raw:
        route_map.setdefault(int(page_index), set()).add("image")
    return [
        {
            "page_index": page_index,
            "routes": [route for route in ("text", "image") if route in routes],
        }
        for page_index, routes in sorted(route_map.items(), key=lambda item: item[0])
    ]


def build_page_source(
    doc_id: str,
    extract_root: str | Path,
    page_index: int,
) -> Dict[str, Any]:
    """Build page source metadata using BaseDataset-compatible paths first."""

    paths = build_mdocagent_extract_paths(extract_root, doc_id, page_index)
    text_path = find_existing_file(list(paths["text_candidate_paths"]))
    image_path = find_existing_file(list(paths["image_candidate_paths"]))
    page_text = text_path.read_text(encoding="utf-8", errors="replace") if text_path else None
    layout_blocks = build_basic_layout_blocks(
        doc_id=doc_id,
        page_index=page_index,
        page_text=page_text,
        has_page_image=image_path is not None,
    )
    return {
        "page_index": int(page_index),
        "page_text_path": str(text_path) if text_path else None,
        "page_image_path": str(image_path) if image_path else None,
        "has_page_text": text_path is not None,
        "has_page_image": image_path is not None,
        "layout_block_ids": [block["block_id"] for block in layout_blocks],
    }


def build_preflight_blocking_reasons(
    candidate_page_routes: List[Dict[str, Any]],
    candidate_page_sources: List[Dict[str, Any]],
) -> List[str]:
    reasons: set[str] = set()
    if not candidate_page_routes:
        reasons.add("no_candidate_page_routes")
    elif not any(source["has_page_text"] or source["has_page_image"] for source in candidate_page_sources):
        reasons.add("missing_all_candidate_sources")
    return sorted(reasons)


def select_trial_candidate_from_stage2_file(
    stage2_json: str | Path,
    output_path: str | Path | None = None,
    extract_root: str | Path = "tmp/MMLongBench",
) -> Dict[str, Any]:
    records = read_json_or_jsonl_records(stage2_json)
    report = select_trial_candidate_from_stage2_records(records, extract_root=extract_root)
    if output_path is not None:
        write_json(report, output_path)
    return report


def select_trial_candidate_from_stage2_records(
    records: Iterable[Mapping[str, Any]],
    extract_root: str | Path = "tmp/MMLongBench",
) -> Dict[str, Any]:
    candidates: List[Dict[str, Any]] = []
    for record_index, record in enumerate(records):
        stage2 = record.get("stage2", {})
        if not isinstance(stage2, dict):
            continue
        candidates.extend(build_record_trial_candidates(record, record_index, extract_root))

    selected = select_best_trial_candidate(candidates)
    return {
        "selection_passed": selected is not None,
        "blocking_reasons": [] if selected is not None else ["no_valid_single_page_trial_candidate"],
        "selected": selected,
        "selection_policy": {
            "priority_order": [
                "valid_explicit_page_with_image",
                "image_top_10_first_available",
                "retrieval_union_first_available",
            ],
            "uses_answer": False,
            "uses_evidence_pages": False,
            "uses_binary_correctness": False,
        },
    }


def build_record_trial_candidates(
    record: Mapping[str, Any],
    record_index: int,
    extract_root: str | Path = "tmp/MMLongBench",
) -> List[Dict[str, Any]]:
    stage2 = record.get("stage2", {})
    if not isinstance(stage2, dict) or not stage2.get("preflight", {}).get("passed", False):
        return []
    route_pages = _candidate_route_pages(stage2)
    page_sources_by_index = {
        page_index: build_page_source(str(record.get("doc_id")), extract_root, page_index)
        for page_index in route_pages
    }
    valid_explicit_pages = get_valid_explicit_page_indices(record, extract_root)
    explicit_refs = parse_question_constraints(str(record.get("question", ""))).get("explicit_page_references", [])
    image_unique_pages = _candidate_route_pages(stage2, required_route="image")
    retrieval_candidate_pages = route_pages

    candidates: List[Dict[str, Any]] = []
    for order, page_index in enumerate(valid_explicit_pages):
        source = page_sources_by_index.get(page_index)
        if page_source_has_image(source):
            candidates.append(
                build_trial_candidate(record, record_index, page_index, source, "valid_explicit_page_with_image", 0, order)
            )

    if not explicit_refs:
        for order, page_index in enumerate(image_unique_pages):
            source = page_sources_by_index.get(page_index)
            if page_source_has_image(source):
                candidates.append(
                    build_trial_candidate(record, record_index, page_index, source, "image_top_10_first_available", 1, order)
                )
                break

    for order, page_index in enumerate(retrieval_candidate_pages):
        source = page_sources_by_index.get(page_index)
        if page_source_has_image(source):
            candidates.append(
                build_trial_candidate(record, record_index, page_index, source, "retrieval_union_first_available", 2, order)
            )
            break

    return candidates


def get_valid_explicit_page_indices(record: Mapping[str, Any], extract_root: str | Path) -> List[int]:
    """Compute valid explicit page indices at runtime without storing them in stage2."""

    doc_id = str(record.get("doc_id"))
    question_constraints = parse_question_constraints(str(record.get("question", "")))
    page_count_info = infer_document_page_count(doc_id=doc_id, pdf_root=None, extract_root=extract_root)
    explicit_validation = validate_explicit_page_references_against_page_count(
        {"question_constraints": question_constraints},
        page_count_info,
    )
    return [int(page_index) for page_index in explicit_validation.get("valid_explicit_page_indices", [])]


def _candidate_route_pages(stage2: Mapping[str, Any], required_route: str | None = None) -> List[int]:
    pages = []
    for item in stage2.get("candidate_page_routes", []) or []:
        if not isinstance(item, dict) or item.get("page_index") is None:
            continue
        routes = item.get("routes", [])
        if required_route is not None and required_route not in routes:
            continue
        pages.append(int(item["page_index"]))
    return pages


def build_trial_candidate(
    record: Mapping[str, Any],
    record_index: int,
    page_index: int,
    page_source: Mapping[str, Any],
    selection_reason: str,
    priority_rank: int,
    page_order: int,
) -> Dict[str, Any]:
    return {
        "record_index": int(record_index),
        "doc_id": record.get("doc_id"),
        "question": record.get("question"),
        "page_index": int(page_index),
        "page_number_one_based": int(page_index) + 1,
        "selection_reason": selection_reason,
        "page_image_path": page_source.get("page_image_path"),
        "layout_block_ids": list(page_source.get("layout_block_ids", [])),
        "_priority_rank": int(priority_rank),
        "_page_order": int(page_order),
    }


def select_best_trial_candidate(candidates: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    ordered = sorted(
        candidates,
        key=lambda item: (
            int(item["_priority_rank"]),
            int(item["record_index"]),
            int(item["_page_order"]),
        ),
    )
    if not ordered:
        return None
    selected = dict(ordered[0])
    selected.pop("_priority_rank", None)
    selected.pop("_page_order", None)
    return selected


def page_source_has_image(page_source: Mapping[str, Any] | None) -> bool:
    return bool(page_source and page_source.get("has_page_image") and page_source.get("page_image_path"))


def build_single_page_trial_summary(
    provider: str,
    model_name: str,
    record_id: str,
    doc_id: str,
    page_index: int,
    raw_output_log_path: str | Path,
    artifact_store_path: str | Path,
    num_raw_artifacts: int,
    num_valid_artifacts: int,
    num_validation_issues: int,
    single_page_smoke_test_passed: bool,
) -> Dict[str, Any]:
    return {
        "step": "7B",
        "provider": provider,
        "model_name": model_name,
        "record_id": record_id,
        "doc_id": doc_id,
        "page_index": int(page_index),
        "raw_output_log_path": str(raw_output_log_path),
        "artifact_store_path": str(artifact_store_path),
        "num_raw_artifacts": int(num_raw_artifacts),
        "num_valid_artifacts": int(num_valid_artifacts),
        "num_validation_issues": int(num_validation_issues),
        "single_page_smoke_test_passed": bool(single_page_smoke_test_passed),
    }


def write_single_page_trial_summary(summary: Mapping[str, Any], output_path: str | Path) -> None:
    forbidden = sorted(key for key in SUMMARY_FORBIDDEN_FIELDS if contains_key(summary, key))
    if forbidden:
        raise ValueError(f"Summary contains forbidden fields: {forbidden}")
    write_json(dict(summary), output_path)


def contains_key(value: Any, key: str) -> bool:
    if isinstance(value, dict):
        return key in value or any(contains_key(child, key) for child in value.values())
    if isinstance(value, list):
        return any(contains_key(child, key) for child in value)
    return False


def write_json(value: Any, output_path: str | Path) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")
