"""Consolidated Stage 2 module.

Generated by module consolidation; public behavior is preserved.
"""

from __future__ import annotations


# ---- from raw_output_log.py ----


from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
from typing import Any, Dict, Optional


@dataclass
class RawCompilerOutputLogEntry:
    doc_id: str
    page_index: int
    provider: str
    model_name: Optional[str]
    compiler_version: str
    prompt_version: str
    raw_output: Dict[str, Any]
    raw_output_hash: str
    stage: str
    created_at: str
    raw_text: Optional[str] = None
    provider_error_type: Optional[str] = None
    provider_error_message: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


def hash_raw_output(raw_output: Dict[str, Any]) -> str:
    """Return a stable sha256 hash for a raw output dict."""

    serialized = json.dumps(raw_output, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def build_raw_output_log_entry(
    doc_id: str,
    page_index: int,
    provider: str,
    model_name: Optional[str],
    compiler_version: str,
    prompt_version: str,
    raw_output: Dict[str, Any],
    stage: str = "stage2_compiler",
    raw_text: Optional[str] = None,
    provider_error_type: Optional[str] = None,
    provider_error_message: Optional[str] = None,
) -> RawCompilerOutputLogEntry:
    """Build a raw output log entry without evaluation-only fields or secrets."""

    return RawCompilerOutputLogEntry(
        doc_id=doc_id,
        page_index=page_index,
        provider=provider,
        model_name=model_name,
        compiler_version=compiler_version,
        prompt_version=prompt_version,
        raw_output=raw_output,
        raw_output_hash=hash_raw_output(raw_output),
        stage=stage,
        created_at=datetime.now(timezone.utc).isoformat(),
        raw_text=raw_text,
        provider_error_type=provider_error_type,
        provider_error_message=provider_error_message,
    )


def write_raw_output_log(path: str | Path, entry: RawCompilerOutputLogEntry) -> None:
    """Append one raw compiler output entry to a JSONL file."""

    log_path = Path(path)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as file_obj:
        file_obj.write(json.dumps(entry.to_dict(), ensure_ascii=False))
        file_obj.write("\n")

# ---- from discard_log.py ----


from dataclasses import asdict, dataclass, field
import json
from pathlib import Path
from typing import Any, Dict, Optional

from .artifact_schema import ValidationIssue


@dataclass
class DiscardLogEntry:
    doc_id: Optional[str]
    page_index: Optional[int]
    artifact_id: Optional[str]
    error_type: str
    message: str
    field_path: Optional[str]
    details: Dict[str, Any] = field(default_factory=dict)
    stage: str = "stage2_validation"
    compiler_version: str = "unversioned"

    def to_dict(self) -> Dict[str, Any]:
        return serialize_discard_log_entry(self)


def issue_to_discard_log_entry(
    issue: ValidationIssue,
    stage: str,
    compiler_version: str,
) -> DiscardLogEntry:
    return DiscardLogEntry(
        doc_id=issue.doc_id,
        page_index=issue.page_index,
        artifact_id=issue.artifact_id,
        error_type=issue.error_type.value,
        message=issue.message,
        field_path=issue.field_path,
        details=dict(issue.details),
        stage=stage,
        compiler_version=compiler_version,
    )


def serialize_discard_log_entry(entry: DiscardLogEntry) -> Dict[str, Any]:
    return asdict(entry)


def write_discard_log_entry(path: str | Path, entry: DiscardLogEntry) -> None:
    log_path = Path(path)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as file_obj:
        file_obj.write(json.dumps(serialize_discard_log_entry(entry), ensure_ascii=False))
        file_obj.write("\n")

# ---- from run_manifest.py ----


from datetime import datetime, timezone
from pathlib import Path
import subprocess
from typing import Any, Dict


DEFAULT_RUNTIME_NOTES = {
    "predict_py_modified": True,
    "multi_agent_system_modified": True,
    "stage2_depends_on_predict_py": False,
    "stage2_depends_on_multi_agent_system": False,
}

FORBIDDEN_MANIFEST_FIELDS = {
    "api_key",
    "answer",
    "evidence_pages",
    "binary_correctness",
}


def build_stage2_run_manifest(
    stage: str,
    script_name: str,
    config_path: str,
    provider: str,
    model_name: str,
    output_dir: str,
    real_api_called: bool,
    limits: dict,
    runtime_notes: dict | None = None,
) -> dict:
    """Build a secret-free Stage 2 run manifest without calling providers."""

    merged_runtime_notes: Dict[str, Any] = dict(DEFAULT_RUNTIME_NOTES)
    if runtime_notes:
        merged_runtime_notes.update(_strip_forbidden_keys(runtime_notes))

    manifest = {
        "stage": stage,
        "script_name": script_name,
        "git_commit": _current_git_commit(),
        "config_path": str(config_path),
        "provider": provider,
        "model_name": model_name,
        "real_api_called": bool(real_api_called),
        "limits": _strip_forbidden_keys(dict(limits or {})),
        "runtime_notes": merged_runtime_notes,
        "output_dir": str(output_dir),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    forbidden = sorted(field for field in FORBIDDEN_MANIFEST_FIELDS if _contains_key(manifest, field))
    if forbidden:
        raise ValueError(f"Run manifest contains forbidden fields: {forbidden}")
    return manifest


def write_stage2_run_manifest(manifest: dict, path: str | Path) -> None:
    """Write a Stage 2 run manifest as pretty JSON."""

    import json

    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")


def _current_git_commit() -> str:
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except Exception:
        return "unknown"
    return completed.stdout.strip() or "unknown"


def _strip_forbidden_keys(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: _strip_forbidden_keys(child)
            for key, child in value.items()
            if key not in FORBIDDEN_MANIFEST_FIELDS
        }
    if isinstance(value, list):
        return [_strip_forbidden_keys(child) for child in value]
    return value


def _contains_key(value: Any, key: str) -> bool:
    if isinstance(value, dict):
        return key in value or any(_contains_key(child, key) for child in value.values())
    if isinstance(value, list):
        return any(_contains_key(child, key) for child in value)
    return False
