"""Consolidated Stage 2 module.

Generated by module consolidation; public behavior is preserved.
"""

from __future__ import annotations


# ---- from layout_parser.py ----


from typing import Any, Dict, List, Optional


TEXT_BLOCK_SIZE = 1000


def build_basic_layout_blocks(
    doc_id: str,
    page_index: int,
    page_text: Optional[str],
    has_page_image: bool,
) -> List[Dict[str, Any]]:
    """Create deterministic source blocks for page text and full-page images."""

    _ = doc_id
    page_index = int(page_index)
    blocks: List[Dict[str, Any]] = []

    if page_text:
        chunks = [
            page_text[index : index + TEXT_BLOCK_SIZE]
            for index in range(0, len(page_text), TEXT_BLOCK_SIZE)
        ]
        for chunk_index, chunk in enumerate(chunks):
            normalized_chunk = chunk.strip()
            if normalized_chunk:
                blocks.append(
                    {
                        "block_id": f"p{page_index:03d}_text_{chunk_index:04d}",
                        "block_type": "text_block",
                        "page_index": page_index,
                        "bbox": None,
                        "text": normalized_chunk,
                    }
                )

    if has_page_image:
        blocks.append(
            {
                "block_id": f"p{page_index:03d}_full_page_image",
                "block_type": "full_page_image",
                "page_index": page_index,
                "bbox": None,
                "text": None,
            }
        )

    return blocks

# ---- from page_loader.py ----


from pathlib import Path
from typing import Any, Dict, List, Optional

from .index_builder import build_mdocagent_extract_paths


def normalize_doc_name(doc_id: str) -> str:
    """Return the document name used by extracted page files."""

    return doc_id[:-4] if doc_id.endswith(".pdf") else doc_id


def find_existing_file(candidate_paths: List[Path]) -> Optional[Path]:
    """Return the first existing file from candidate paths."""

    for path in candidate_paths:
        if path.is_file():
            return path
    return None


def load_page_content(
    canonical_record: Dict[str, Any],
    extract_path: str | Path,
    page_index: int,
) -> Dict[str, Any]:
    """Load page text and image paths for one page index.

    This function intentionally reads only canonical document metadata and the
    requested page index. It never derives content from evaluation-only fields.
    """

    doc_id = canonical_record["document"]["doc_id"]
    doc_name = normalize_doc_name(doc_id)
    root = Path(extract_path)
    page_index = int(page_index)

    mdocagent_paths = build_mdocagent_extract_paths(root, doc_id, page_index)
    text_candidate_paths = list(mdocagent_paths["text_candidate_paths"])
    image_candidate_paths = list(mdocagent_paths["image_candidate_paths"])

    text_path = find_existing_file(text_candidate_paths)
    image_path = find_existing_file(image_candidate_paths)
    page_text = text_path.read_text(encoding="utf-8", errors="replace") if text_path else None

    return {
        "doc_id": doc_id,
        "page_index": page_index,
        "page_text": page_text,
        "page_text_path": str(text_path) if text_path else None,
        "page_image_path": str(image_path) if image_path else None,
        "has_page_text": page_text is not None,
        "has_page_image": image_path is not None,
        "text_paths_checked": [str(path) for path in text_candidate_paths],
        "image_paths_checked": [str(path) for path in image_candidate_paths],
    }


def build_text_candidate_paths(root: Path, doc_name: str, page_index: int) -> List[Path]:
    """Build supported candidate text paths in priority order."""

    return [
        root / f"{doc_name}_{page_index}.txt",
        root / f"{doc_name}_{page_index:03d}.txt",
        root / "texts" / f"{doc_name}_{page_index}.txt",
        root / "texts" / f"{doc_name}_{page_index:03d}.txt",
        root / "texts" / f"page_{page_index}.txt",
        root / "texts" / f"page_{page_index:03d}.txt",
    ]


def build_image_candidate_paths(root: Path, doc_name: str, page_index: int) -> List[Path]:
    """Build supported candidate image paths in priority order."""

    return [
        root / f"{doc_name}_{page_index}.png",
        root / f"{doc_name}_{page_index:03d}.png",
        root / "images" / f"{doc_name}_{page_index}.png",
        root / "images" / f"{doc_name}_{page_index:03d}.png",
        root / "images" / f"page_{page_index}.png",
        root / "images" / f"page_{page_index:03d}.png",
    ]

# ---- from page_preparer.py ----


from pathlib import Path
from typing import Any, Dict, List



def prepare_pages_for_compilation(
    canonical_record: Dict[str, Any],
    extract_path: str | Path,
) -> Dict[str, Any]:
    """Create page compilation inputs for all pages in pages_to_compile."""

    doc_id = canonical_record["document"]["doc_id"]
    pages_to_compile = canonical_record["compilation_plan"]["pages_to_compile"]
    candidate_pool = canonical_record.get("candidate_pool", {})
    explicit_pages = set(candidate_pool.get("explicit_constraint_pages", []))
    retrieval_pages = set(candidate_pool.get("retrieval_candidate_pages", []))

    pages: List[Dict[str, Any]] = []
    errors: List[Dict[str, Any]] = []

    for raw_page_index in pages_to_compile:
        page_index = int(raw_page_index)
        page_content = load_page_content(
            canonical_record=canonical_record,
            extract_path=extract_path,
            page_index=page_index,
        )
        layout_blocks = build_basic_layout_blocks(
            doc_id=doc_id,
            page_index=page_index,
            page_text=page_content["page_text"],
            has_page_image=page_content["has_page_image"],
        )

        pages.append(
            {
                "doc_id": doc_id,
                "page_index": page_index,
                "page_text": page_content["page_text"],
                "page_text_path": page_content["page_text_path"],
                "page_image_path": page_content["page_image_path"],
                "has_page_text": page_content["has_page_text"],
                "has_page_image": page_content["has_page_image"],
                "layout_blocks": layout_blocks,
            }
        )

        if not layout_blocks:
            errors.append(
                {
                    "error_type": "missing_source_anchors",
                    "doc_id": doc_id,
                    "page_index": page_index,
                    "required_by": _build_required_by(page_index, explicit_pages, retrieval_pages),
                    "text_paths_checked": page_content["text_paths_checked"],
                    "image_paths_checked": page_content["image_paths_checked"],
                }
            )

    return {
        "doc_id": doc_id,
        "pages": pages,
        "errors": errors,
    }


def _build_required_by(
    page_index: int,
    explicit_pages: set[int],
    retrieval_pages: set[int],
) -> List[str]:
    required_by: List[str] = []
    if page_index in explicit_pages:
        required_by.append("explicit_page_reference")
    if page_index in retrieval_pages:
        required_by.append("retrieval_candidate_page")
    return required_by
