"""Consolidated Stage 2 module.

Generated by module consolidation; public behavior is preserved.
"""

from __future__ import annotations


# ---- from api_config.py ----


from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class ApiRunConfig:
    enable_real_api: bool = False
    provider: str = "siliconflow"
    model_name: Optional[str] = None
    max_pages: int = 1
    max_pages_total: Optional[int] = None
    max_pages_per_call: int = 1
    temperature: float = 0.0
    timeout_seconds: int = 120
    raw_output_dir: str | Path | None = None
    discard_log_dir: str | Path | None = None
    api_base_url: Optional[str] = None
    api_key_env_var: str = "SILICONFLOW_API_KEY"
    api_key: Optional[str] = field(default=None, repr=False)
    max_tokens: Optional[int] = None
    image_payload_mode: str = "image_url"


def assert_real_api_allowed(config: ApiRunConfig) -> None:
    """Enforce explicit single-page opt-in before any real API call."""

    if not config.enable_real_api:
        raise RuntimeError("Real API usage is disabled. Set enable_real_api=True explicitly.")
    if int(getattr(config, "max_pages_per_call", 1)) != 1:
        raise RuntimeError("Real provider calls are limited to max_pages_per_call=1.")
    max_pages_total = getattr(config, "max_pages_total", None)
    if max_pages_total is None:
        max_pages_total = getattr(config, "max_pages", None)
    if max_pages_total is None or int(max_pages_total) < 1:
        raise RuntimeError("Real API usage requires a finite positive max_pages_total.")
    if not config.model_name:
        raise RuntimeError("Real API usage requires a non-empty model_name.")

# ---- from provider_errors.py ----


from typing import Optional


class ProviderError(Exception):
    """Base class for provider adapter failures."""

    def __init__(
        self,
        message: str,
        raw_text: Optional[str] = None,
        parse_failure_type: Optional[str] = None,
        contains_json_like_block: Optional[bool] = None,
        schema_missing_fields: Optional[list[str]] = None,
    ) -> None:
        super().__init__(message)
        self.raw_text = raw_text
        self.parse_failure_type = parse_failure_type
        self.contains_json_like_block = contains_json_like_block
        self.schema_missing_fields = list(schema_missing_fields or [])


class ProviderNotConfiguredError(ProviderError):
    """Raised when the requested provider is not configured or supported."""


class ProviderResponseFormatError(ProviderError):
    """Raised when a provider response cannot be parsed as a JSON object."""


class ProviderDependencyError(ProviderError):
    """Raised when a required provider runtime dependency is unavailable."""


class ProviderDisabledError(ProviderError):
    """Raised when real API usage is not explicitly enabled."""

# ---- from provider_client.py ----


import json
import base64
import inspect
import mimetypes
import os
from typing import Any, Dict, Optional
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen



DEFAULT_PROVIDER_BASE_URLS = {
    "siliconflow": "https://api.siliconflow.cn/v1",
}


class CompatibleChatJsonProvider:
    """Small HTTP adapter for providers exposing chat-completions style JSON responses."""

    def __init__(self, api_config: ApiRunConfig) -> None:
        self.api_config = api_config

    def generate_json(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
        image_path: str | Path | None = None,
    ) -> Dict[str, Any]:
        """Request one JSON object from a configured provider without validation or repair."""

        assert_real_api_allowed(self.api_config)
        api_key = _read_api_key(self.api_config)
        request_body = _build_request_body(
            model_name=str(self.api_config.model_name),
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            schema_dict=schema_dict,
            temperature=self.api_config.temperature,
            max_tokens=self.api_config.max_tokens,
            image_path=image_path,
            image_payload_mode=self.api_config.image_payload_mode,
        )
        request = Request(
            _resolve_chat_completions_url(self.api_config),
            data=json.dumps(request_body, ensure_ascii=False).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            method="POST",
        )
        try:
            with urlopen(request, timeout=self.api_config.timeout_seconds) as response:
                raw_text = response.read().decode("utf-8")
        except HTTPError as exc:
            raw_text = _read_error_body(exc)
            raise ProviderResponseFormatError(
                f"Provider HTTP error: {exc.code}",
                raw_text=raw_text,
            ) from exc
        except URLError as exc:
            raise ProviderError(f"Provider request failed: {exc.reason}") from exc

        return _parse_chat_completion_json(raw_text)


def _build_request_body(
    model_name: str,
    system_prompt: str,
    user_prompt: str,
    schema_dict: Dict[str, Any],
    temperature: float,
    max_tokens: Optional[int],
    image_path: str | Path | None = None,
    image_payload_mode: str = "image_url",
) -> Dict[str, Any]:
    _ = schema_dict
    payload_audit = describe_image_payload(image_path=image_path, image_payload_mode=image_payload_mode)
    request_body = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": _build_user_message_content(user_prompt, image_path, image_payload_mode)},
        ],
        "temperature": temperature,
        "stream": False,
        "response_format": {"type": "json_object"},
        "metadata": {
            "stage": "stage2_artifact_compilation",
            "schema_name": "page_artifact_output",
            "schema_version": "stage2_artifact_schema_v1",
            "image_payload_mode": image_payload_mode,
            "actual_image_payload_kind": payload_audit["actual_image_payload_kind"],
            "image_payload_sent": payload_audit["image_payload_sent"],
        },
    }
    if max_tokens is not None:
        request_body["max_tokens"] = max_tokens
    return request_body


def _build_user_message_content(
    user_prompt: str,
    image_path: str | Path | None = None,
    image_payload_mode: str = "image_url",
) -> Any:
    if not image_path or image_payload_mode == "none":
        return user_prompt
    if image_payload_mode not in {"image_url", "base64"}:
        raise ProviderError(f"Unsupported image_payload_mode: {image_payload_mode}")
    return [
        {"type": "text", "text": user_prompt},
        {"type": "image_url", "image_url": {"url": _build_image_data_url(image_path)}},
    ]


def describe_image_payload(
    image_path: str | Path | None,
    image_payload_mode: str = "image_url",
) -> Dict[str, Any]:
    """Return public-safe image payload audit metadata."""

    if not image_path or image_payload_mode == "none":
        return {"image_payload_mode": image_payload_mode, "actual_image_payload_kind": "none", "image_payload_sent": False}
    if image_payload_mode not in {"image_url", "base64"}:
        raise ProviderError(f"Unsupported image_payload_mode: {image_payload_mode}")
    if not Path(image_path).is_file():
        return {"image_payload_mode": image_payload_mode, "actual_image_payload_kind": "none", "image_payload_sent": False}
    return {
        "image_payload_mode": image_payload_mode,
        "actual_image_payload_kind": "base64_data_url",
        "image_payload_sent": True,
    }


def _build_image_data_url(image_path: str | Path) -> str:
    path = Path(image_path)
    if not path.is_file():
        raise ProviderError(f"Image payload path does not exist: {path}")
    mime_type = _guess_image_mime_type(path)
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def _guess_image_mime_type(path: Path) -> str:
    guessed_type, _ = mimetypes.guess_type(str(path))
    if guessed_type and guessed_type.startswith("image/"):
        return guessed_type
    suffix = path.suffix.lower()
    if suffix in {".jpg", ".jpeg"}:
        return "image/jpeg"
    if suffix == ".webp":
        return "image/webp"
    return "image/png"


def _read_api_key(api_config: ApiRunConfig) -> str:
    direct_api_key = getattr(api_config, "api_key", None)
    if direct_api_key:
        return str(direct_api_key)
    api_key = os.environ.get(api_config.api_key_env_var, "")
    if not api_key.strip():
        api_key = _read_api_key_from_persistent_env(api_config.api_key_env_var)
    if not api_key.strip():
        raise ProviderNotConfiguredError(
            f"Provider API key environment variable is not set: {api_config.api_key_env_var}"
        )
    return api_key


def _read_api_key_from_persistent_env(env_var_name: str) -> str:
    """Read a provider key from private machine-local env files.

    This is a fallback for non-interactive SSH commands that do not source
    ~/.bashrc or ~/.profile. It intentionally reads only simple KEY=VALUE or
    export KEY=VALUE lines and never writes credentials into repo files.
    """

    for env_path in _persistent_env_paths():
        value = _read_env_file_value(env_path, env_var_name)
        if value.strip():
            return value
    return ""


def _persistent_env_paths() -> list[Path]:
    paths = [Path.home() / ".config" / "mdocagent" / "stage2.env"]
    try:
        paths.append(Path("/etc/environment"))
    except Exception:
        pass
    return paths


def _read_env_file_value(path: Path, env_var_name: str) -> str:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return ""
    prefix = f"{env_var_name}="
    export_prefix = f"export {env_var_name}="
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith(export_prefix):
            return _strip_env_value(stripped[len(export_prefix):])
        if stripped.startswith(prefix):
            return _strip_env_value(stripped[len(prefix):])
    return ""


def _strip_env_value(value: str) -> str:
    stripped = value.strip()
    if len(stripped) >= 2 and stripped[0] == stripped[-1] and stripped[0] in {"'", '"'}:
        return stripped[1:-1]
    return stripped


def _resolve_chat_completions_url(api_config: ApiRunConfig) -> str:
    base_url = api_config.api_base_url or os.environ.get("STAGE2_API_BASE_URL")
    if not base_url:
        base_url = DEFAULT_PROVIDER_BASE_URLS.get(api_config.provider)
    if not base_url:
        raise ProviderNotConfiguredError(
            f"Provider base URL is not configured for provider {api_config.provider!r}."
        )
    normalized_base = base_url.rstrip("/")
    if normalized_base.endswith("/chat/completions"):
        return normalized_base
    return f"{normalized_base}/chat/completions"


def _parse_chat_completion_json(raw_text: str) -> Dict[str, Any]:
    try:
        response_object = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        try:
            return _parse_json_object_from_text(raw_text)
        except ProviderResponseFormatError:
            raise _provider_response_format_error(
                "Provider response was not valid JSON.",
                raw_text=raw_text,
                parse_failure_type="http_response_not_json",
            ) from exc

    if isinstance(response_object, dict) and _looks_like_page_artifact_output(response_object):
        return response_object

    content = _extract_message_content(response_object)
    if isinstance(content, dict):
        return content
    if not isinstance(content, str):
        raise _provider_response_format_error(
            "Provider response did not contain JSON text.",
            raw_text=raw_text,
            parse_failure_type="missing_message_content",
        )

    try:
        parsed = _parse_json_object_from_text(content)
    except ProviderResponseFormatError as exc:
        raise _provider_response_format_error(
            "Provider message content was not valid JSON.",
            raw_text=content,
            parse_failure_type="message_content_not_json",
        ) from exc
    if not isinstance(parsed, dict):
        raise _provider_response_format_error(
            "Provider message JSON was not an object.",
            raw_text=content,
            parse_failure_type="message_json_not_object",
        )
    return parsed


def _extract_message_content(response_object: Any) -> Optional[Any]:
    if not isinstance(response_object, dict):
        return None
    choices = response_object.get("choices")
    if not isinstance(choices, list) or not choices:
        return response_object.get("content")
    first_choice = choices[0]
    if not isinstance(first_choice, dict):
        return None
    message = first_choice.get("message")
    if isinstance(message, dict):
        content = message.get("content")
        if isinstance(content, list):
            return _join_content_parts(content)
        return content
    return first_choice.get("text")


def _join_content_parts(content_parts: list[Any]) -> str:
    text_parts = []
    for part in content_parts:
        if isinstance(part, dict) and isinstance(part.get("text"), str):
            text_parts.append(part["text"])
        elif isinstance(part, str):
            text_parts.append(part)
    return "".join(text_parts)


def _strip_json_fence(text: str) -> str:
    stripped = text.strip()
    fence = chr(96) * 3
    if stripped.startswith(fence):
        lines = stripped.splitlines()
        if lines and lines[0].startswith(fence):
            lines = lines[1:]
        if lines and lines[-1].strip() == fence:
            lines = lines[:-1]
        return "\n".join(lines).strip()
    return stripped


def _parse_json_object_from_text(text: str) -> Dict[str, Any]:
    candidates = [text.strip(), _strip_json_fence(text)]
    candidates.extend(_extract_fenced_json_candidates(text))
    candidates.extend(_extract_balanced_json_object_candidates(text))
    seen: set[str] = set()
    saw_json_like = False
    for candidate in candidates:
        candidate = candidate.strip()
        if not candidate or candidate in seen:
            continue
        seen.add(candidate)
        saw_json_like = saw_json_like or _contains_json_like_block(candidate)
        try:
            parsed = json.loads(candidate)
        except json.JSONDecodeError:
            continue
        if isinstance(parsed, dict):
            return parsed
        raise _provider_response_format_error(
            "Provider JSON text was not an object.",
            raw_text=text,
            parse_failure_type="json_not_object",
        )
    raise _provider_response_format_error(
        "Provider text did not contain a parseable JSON object.",
        raw_text=text,
        parse_failure_type="json_object_not_found" if saw_json_like else "json_like_block_absent",
    )


def _extract_fenced_json_candidates(text: str) -> list[str]:
    fence = chr(96) * 3
    candidates: list[str] = []
    parts = text.split(fence)
    for index in range(1, len(parts), 2):
        block = parts[index].strip()
        if not block:
            continue
        lines = block.splitlines()
        if lines and lines[0].strip().lower() in {"json", "json_object"}:
            lines = lines[1:]
        candidates.append("\n".join(lines).strip())
    return candidates


def _extract_balanced_json_object_candidates(text: str) -> list[str]:
    candidates: list[str] = []
    starts = [index for index, char in enumerate(text) if char == "{"]
    for start in starts:
        depth = 0
        in_string = False
        escaped = False
        for index in range(start, len(text)):
            char = text[index]
            if in_string:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == '"':
                    in_string = False
                continue
            if char == '"':
                in_string = True
            elif char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    candidates.append(text[start:index + 1])
                    break
    return candidates


def _provider_response_format_error(
    message: str,
    raw_text: str,
    parse_failure_type: str,
) -> ProviderResponseFormatError:
    return ProviderResponseFormatError(
        message,
        raw_text=raw_text,
        parse_failure_type=parse_failure_type,
        contains_json_like_block=_contains_json_like_block(raw_text),
        schema_missing_fields=_schema_missing_fields(raw_text),
    )


def _contains_json_like_block(text: str) -> bool:
    stripped = text.strip()
    return "{" in stripped and "}" in stripped


def _schema_missing_fields(text: str) -> list[str]:
    for candidate in [text.strip(), _strip_json_fence(text), *_extract_fenced_json_candidates(text), *_extract_balanced_json_object_candidates(text)]:
        try:
            parsed = json.loads(candidate)
        except Exception:
            continue
        if isinstance(parsed, dict):
            return [field for field in ("doc_id", "page_index", "artifacts") if field not in parsed]
    return []


def _looks_like_page_artifact_output(value: Dict[str, Any]) -> bool:
    return {"doc_id", "page_index", "artifacts"}.issubset(value.keys())


def _read_error_body(error: HTTPError) -> str:
    try:
        return error.read().decode("utf-8")
    except Exception:
        return ""

# ---- from mock_artifact_outputs.py ----


from pathlib import Path
import re
from typing import Any, Dict, List, Optional


MOCK_COMPILER_METADATA = {
    "compiler_name": "mock_artifact_output_builder",
    "compiler_version": "mock_stage2_dry_run",
}


def build_mock_page_artifact_output(
    doc_id: str,
    page_index: int,
    layout_blocks: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Build deterministic mock artifacts anchored to existing layout blocks."""

    full_page_block = _first_block_of_type(layout_blocks, "full_page_image")
    text_blocks = [block for block in layout_blocks if isinstance(block, dict) and block.get("block_type") == "text_block"]
    text_block = text_blocks[0] if text_blocks else None
    artifacts: List[Dict[str, Any]] = []

    if full_page_block is not None:
        artifacts.append(_build_visual_observation(doc_id, page_index, full_page_block, len(artifacts) + 1))
        artifacts.append(_build_visual_region(doc_id, page_index, full_page_block, len(artifacts) + 1))
        artifacts.append(_build_figure(doc_id, page_index, full_page_block, len(artifacts) + 1))
    if text_block is not None:
        artifacts.append(_build_text_span(doc_id, page_index, text_block, len(artifacts) + 1))
        artifacts.append(_build_section_header(doc_id, page_index, text_block, len(artifacts) + 1))
        artifacts.append(_build_caption(doc_id, page_index, text_block, len(artifacts) + 1))
        artifacts.append(_build_numeric_fact(doc_id, page_index, text_block, len(artifacts) + 1))
        artifacts.append(_build_table(doc_id, page_index, text_block, len(artifacts) + 1))
        artifacts.append(_build_table_cell(doc_id, page_index, text_block, len(artifacts) + 1))

    return {
        "doc_id": doc_id,
        "page_index": page_index,
        "page_id": _page_id(doc_id, page_index),
        "artifacts": artifacts,
        "uncertain_or_unreadable": [],
    }


def _build_visual_observation(
    doc_id: str,
    page_index: int,
    block: Dict[str, Any],
    local_index: int,
) -> Dict[str, Any]:
    source_id = block["block_id"]
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="visual_observation",
        modality="image",
        local_index=local_index,
        locator_id=source_id,
        content="Mock visual observation anchored to the full page image.",
        normalized_content={
            "observation_scope": "full_page",
            "presence": "undetermined",
        },
        source_anchor=_source_anchor(source_id, "full_page_image", page_index, block.get("bbox")),
        locators=[{"locator_kind": "full_page_anchor", "source_id": source_id}],
        source_anchored=True,
        element_locatable=False,
        proof_trace_eligible=False,
    )


def _build_visual_region(
    doc_id: str,
    page_index: int,
    block: Dict[str, Any],
    local_index: int,
) -> Dict[str, Any]:
    source_id = block["block_id"]
    figure_id = f"fig_{page_index:03d}_0001"
    locators = [{"locator_kind": "full_page_anchor", "source_id": source_id}]
    bbox = block.get("bbox")
    if bbox not in (None, [], ""):
        locators.append({"locator_kind": "bbox", "source_id": source_id, "bbox": bbox})
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="visual_region",
        modality="layout",
        local_index=local_index,
        locator_id=figure_id,
        content="Mock visual region candidate anchored to the page image.",
        normalized_content={"figure_id": figure_id, "region_scope": "page_region"},
        source_anchor=_source_anchor(source_id, "full_page_image", page_index, bbox),
        locators=locators,
        source_anchored=True,
        element_locatable=bbox not in (None, [], ""),
        proof_trace_eligible=bbox not in (None, [], ""),
    )


def _build_figure(
    doc_id: str,
    page_index: int,
    block: Dict[str, Any],
    local_index: int,
) -> Dict[str, Any]:
    source_id = block["block_id"]
    figure_id = f"fig_{page_index:03d}_0001"
    bbox = block.get("bbox")
    locators = [{"locator_kind": "full_page_anchor", "source_id": source_id}]
    if bbox not in (None, [], ""):
        locators.extend(
            [
                {"locator_kind": "bbox", "source_id": source_id, "bbox": bbox},
                {"locator_kind": "figure_region", "figure_id": figure_id, "bbox": bbox},
            ]
        )
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="figure",
        modality="image",
        local_index=local_index,
        locator_id=figure_id,
        content="Mock figure candidate anchored to the page image.",
        normalized_content={"figure_id": figure_id},
        source_anchor=_source_anchor(source_id, "full_page_image", page_index, bbox),
        locators=locators,
        source_anchored=True,
        element_locatable=bbox not in (None, [], ""),
        proof_trace_eligible=bbox not in (None, [], ""),
    )


def _build_text_span(
    doc_id: str,
    page_index: int,
    block: Dict[str, Any],
    local_index: int,
) -> Dict[str, Any]:
    source_id = block["block_id"]
    char_start, char_end = _text_offsets(block)
    text_sample = _text_sample(block)
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="text_span",
        modality="text",
        local_index=local_index,
        locator_id=source_id,
        content=text_sample or "Mock text span anchored to a text block.",
        normalized_content={
            "block_id": source_id,
            "char_start": char_start,
            "char_end": char_end,
        },
        source_anchor=_source_anchor(source_id, "text_block", page_index, block.get("bbox")),
        locators=[
            {"locator_kind": "source_block", "block_id": source_id, "source_id": source_id},
            {"locator_kind": "text_offset", "block_id": source_id, "char_start": char_start, "char_end": char_end},
        ],
        source_anchored=True,
        element_locatable=True,
        proof_trace_eligible=True,
    )


def _build_section_header(doc_id: str, page_index: int, block: Dict[str, Any], local_index: int) -> Dict[str, Any]:
    source_id = block["block_id"]
    char_start, char_end = _text_offsets(block)
    section_id = f"section_{page_index:03d}_{_local_suffix(local_index)}"
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="section_header",
        modality="layout",
        local_index=local_index,
        locator_id=section_id,
        content=_first_line(block) or "Mock section header candidate anchored to a text block.",
        normalized_content={"section_id": section_id, "block_id": source_id, "char_start": char_start, "char_end": char_end},
        source_anchor=_source_anchor(source_id, "text_block", page_index, block.get("bbox")),
        locators=[
            {"locator_kind": "source_block", "block_id": source_id, "source_id": source_id},
            {"locator_kind": "section_block", "section_id": section_id, "block_id": source_id},
            {"locator_kind": "text_offset", "block_id": source_id, "char_start": char_start, "char_end": char_end},
        ],
        source_anchored=True,
        element_locatable=True,
        proof_trace_eligible=True,
    )


def _build_caption(doc_id: str, page_index: int, block: Dict[str, Any], local_index: int) -> Dict[str, Any]:
    source_id = block["block_id"]
    caption_id = f"caption_{page_index:03d}_{_local_suffix(local_index)}"
    figure_id = f"fig_{page_index:03d}_0001"
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="caption",
        modality="text",
        local_index=local_index,
        locator_id=caption_id,
        content="Mock caption candidate anchored to a text block.",
        normalized_content={"caption_id": caption_id, "figure_id": figure_id, "block_id": source_id},
        source_anchor=_source_anchor(source_id, "text_block", page_index, block.get("bbox")),
        locators=[
            {"locator_kind": "source_block", "block_id": source_id, "source_id": source_id},
            {"locator_kind": "caption_block", "caption_id": caption_id, "block_id": source_id},
        ],
        source_anchored=True,
        element_locatable=True,
        proof_trace_eligible=True,
    )


def _build_numeric_fact(doc_id: str, page_index: int, block: Dict[str, Any], local_index: int) -> Dict[str, Any]:
    source_id = block["block_id"]
    char_start, char_end = _text_offsets(block)
    value = _first_number(block)
    content = f"Mock numeric fact candidate anchored to a text block: {value}." if value else "Mock numeric fact candidate anchored to a text block."
    normalized_content: Dict[str, Any] = {
        "block_id": source_id,
        "char_start": char_start,
        "char_end": char_end,
    }
    if value is not None:
        normalized_content["value_text"] = value
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="numeric_fact",
        modality="numeric",
        local_index=local_index,
        locator_id=source_id,
        content=content,
        normalized_content=normalized_content,
        source_anchor=_source_anchor(source_id, "text_block", page_index, block.get("bbox")),
        locators=[
            {"locator_kind": "source_block", "block_id": source_id, "source_id": source_id},
            {"locator_kind": "text_offset", "block_id": source_id, "char_start": char_start, "char_end": char_end},
        ],
        source_anchored=True,
        element_locatable=True,
        proof_trace_eligible=True,
    )


def _build_table(doc_id: str, page_index: int, block: Dict[str, Any], local_index: int) -> Dict[str, Any]:
    source_id = block["block_id"]
    table_id = f"table_{page_index:03d}_0001"
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="table",
        modality="table",
        local_index=local_index,
        locator_id=table_id,
        content="Mock table candidate anchored to a text block.",
        normalized_content={"table_id": table_id, "block_id": source_id},
        source_anchor=_source_anchor(source_id, "text_block", page_index, block.get("bbox")),
        locators=[{"locator_kind": "source_block", "block_id": source_id, "source_id": source_id}],
        source_anchored=True,
        element_locatable=True,
        proof_trace_eligible=True,
    )


def _build_table_cell(doc_id: str, page_index: int, block: Dict[str, Any], local_index: int) -> Dict[str, Any]:
    source_id = block["block_id"]
    table_id = f"table_{page_index:03d}_0001"
    return _base_artifact(
        doc_id=doc_id,
        page_index=page_index,
        artifact_type="table_cell",
        modality="table",
        local_index=local_index,
        locator_id=f"{table_id}_r000_c000",
        content="Mock table cell candidate anchored to a text block.",
        normalized_content={"table_id": table_id, "row_index": 0, "column_index": 0, "block_id": source_id},
        source_anchor=_source_anchor(source_id, "text_block", page_index, block.get("bbox")),
        locators=[
            {"locator_kind": "source_block", "block_id": source_id, "source_id": source_id},
            {"locator_kind": "table_cell", "table_id": table_id, "row_index": 0, "column_index": 0},
        ],
        source_anchored=True,
        element_locatable=True,
        proof_trace_eligible=True,
    )


def _base_artifact(
    *,
    doc_id: str,
    page_index: int,
    artifact_type: str,
    modality: str,
    local_index: int,
    locator_id: str,
    content: str,
    normalized_content: Dict[str, Any],
    source_anchor: Dict[str, Any],
    locators: List[Dict[str, Any]],
    source_anchored: bool,
    element_locatable: bool,
    proof_trace_eligible: bool,
) -> Dict[str, Any]:
    source_id = str(source_anchor["source_id"])
    return {
        "artifact_id": _artifact_id(doc_id, page_index, artifact_type, locator_id, local_index),
        "doc_id": doc_id,
        "page_id": _page_id(doc_id, page_index),
        "page_index": int(page_index),
        "artifact_type": artifact_type,
        "modality": modality,
        "content": content,
        "normalized_content": normalized_content,
        "source_anchors": [source_anchor],
        "provenance": {
            "op": "ATOM",
            "sources": [source_id],
        },
        "status": "candidate",
        "validation_status": "candidate",
        "locators": locators,
        "source_anchored": bool(source_anchored),
        "element_locatable": bool(element_locatable),
        "proof_trace_eligible": bool(proof_trace_eligible),
        "compiler_metadata": dict(MOCK_COMPILER_METADATA),
    }


def _source_anchor(source_id: str, anchor_type: str, page_index: int, bbox: Any) -> Dict[str, Any]:
    return {
        "source_id": source_id,
        "anchor_type": anchor_type,
        "page_index": int(page_index),
        "bbox": bbox if bbox not in ([], "") else None,
    }


def _artifact_id(doc_id: str, page_index: int, artifact_type: str, locator_id: str, local_index: int) -> str:
    _ = artifact_type
    parts = [
        _doc_stem(doc_id),
        f"p{int(page_index):03d}",
        _safe_id(locator_id),
        _local_suffix(local_index),
    ]
    return "_".join(part for part in parts if part)


def _page_id(doc_id: str, page_index: int) -> str:
    return f"{doc_id}#p{int(page_index):03d}"


def _local_suffix(local_index: int) -> str:
    return f"{int(local_index):04d}"


def _safe_id(value: Any) -> str:
    return "".join(ch if ch.isalnum() or ch in {"_", "-", "."} else "_" for ch in str(value)).strip("_")


def _text_offsets(block: Dict[str, Any]) -> tuple[int, int]:
    if block.get("char_start") not in (None, "") and block.get("char_end") not in (None, ""):
        return int(block["char_start"]), int(block["char_end"])
    text = str(block.get("text") or "")
    return 0, len(text)


def _text_sample(block: Dict[str, Any], max_chars: int = 240) -> str:
    text = " ".join(str(block.get("text") or "").split())
    return text[:max_chars]


def _first_line(block: Dict[str, Any]) -> str:
    text = str(block.get("text") or "")
    for line in text.splitlines():
        clean = " ".join(line.split())
        if clean:
            return clean[:160]
    return ""


def _first_number(block: Dict[str, Any]) -> str | None:
    match = re.search(r"[-+]?\d+(?:[.,]\d+)?%?", str(block.get("text") or ""))
    return match.group(0) if match else None


def _first_block_of_type(
    layout_blocks: List[Dict[str, Any]],
    block_type: str,
) -> Optional[Dict[str, Any]]:
    for block in layout_blocks:
        if block.get("block_type") == block_type:
            return block
    return None


def _doc_stem(doc_id: str) -> str:
    return Path(doc_id).name.removesuffix(".pdf")

# ---- from compiler_client.py ----


import json
from typing import Any, Dict



class ArtifactCompilerClient:
    """Abstract compiler client interface."""

    def generate_page_artifacts(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
    ) -> Dict[str, Any]:
        raise NotImplementedError


class FakeArtifactCompilerClient(ArtifactCompilerClient):
    """Offline fake compiler client used by default tests and dry runs."""

    def generate_page_artifacts(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
    ) -> Dict[str, Any]:
        _ = system_prompt
        _ = schema_dict
        prompt_payload = json.loads(user_prompt)
        document = prompt_payload["document"]
        return build_mock_page_artifact_output(
            doc_id=document["doc_id"],
            page_index=document["page_index"],
            layout_blocks=prompt_payload.get("layout_blocks", []),
        )


class RealArtifactCompilerClient(ArtifactCompilerClient):
    """Real compiler client skeleton guarded by enable_real_api."""

    def __init__(self, enable_real_api: bool = False, provider_config: Dict[str, Any] | None = None) -> None:
        self.enable_real_api = enable_real_api
        self.provider_config = provider_config or {}

    def generate_page_artifacts(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
    ) -> Dict[str, Any]:
        if not self.enable_real_api:
            raise RuntimeError("Real artifact compiler API is disabled. Pass enable_real_api=True explicitly.")
        raise NotImplementedError("Real provider integration is intentionally not implemented in Step 5.")

# ---- from compiler_prompt.py ----


import json
from typing import Any, Dict

from .artifact_schema import get_allowed_artifact_types


def build_artifact_compiler_system_prompt() -> str:
    """Build the system prompt for a constrained artifact compiler."""

    return "\n".join(
        [
            "You are an evidence artifact compiler.",
            "Convert one document page into typed evidence artifacts.",
            "Do not answer the question.",
            "Do not use gold answers.",
            "Do not infer unsupported facts.",
            "Artifact content must describe page evidence, not a generated answer.",
            "Every artifact must cite source_anchors from the provided layout_blocks.",
            "Artifact status must be candidate before validation.",
            "Do not generate supports / contradicts edges.",
            "Do not generate proof_trace.",
            "Do not output verified / answer_supported / proof_used.",
            "If uncertain, write uncertain_or_unreadable.",
            "Return strict JSON only.",
            "The first output character must be { and the final output character must be }.",
            "Do not wrap JSON in markdown fences.",
            "Do not include explanations, comments, apologies, or prose before or after the JSON object.",
        ]
    )


def build_artifact_compiler_user_prompt(
    canonical_record: Dict[str, Any],
    page_input: Dict[str, Any],
    schema_dict: Dict[str, Any],
) -> str:
    """Build the user prompt from compiler-safe canonical fields and page input."""

    document = canonical_record["document"]
    question = canonical_record["question"]
    question_constraints = canonical_record.get("question_constraints", {})
    compilation_plan = canonical_record.get("compilation_plan", {})
    page_index = int(page_input["page_index"])
    is_explicit_page = _is_explicit_page_constraint(question_constraints, page_index)
    page_requirement = _build_page_requirement(page_input, is_explicit_page)
    page_modality_diagnosis = page_input.get("page_modality_diagnosis", {})

    prompt_payload = {
        "task": "Convert this single page into candidate evidence artifacts.",
        "document": {
            "doc_id": document["doc_id"],
            "page_index": page_index,
            "page_number_one_based": page_index + 1,
        },
        "question": {
            "text": question.get("text"),
            "answer_format": question.get("answer_format"),
        },
        "question_constraints": question_constraints,
        "compilation_plan": {
            "compile_scope": compilation_plan.get("compile_scope"),
            "priority_pages": compilation_plan.get("priority_pages", []),
            "compilation_reasons": compilation_plan.get("compilation_reasons", []),
        },
        "page_requirement": page_requirement,
        "page_modality_diagnosis": page_modality_diagnosis,
        "allowed_artifact_types": get_allowed_artifact_types(),
        "required_json_schema": schema_dict,
        "layout_blocks": page_input.get("layout_blocks", []),
        "page_text": page_input.get("page_text"),
        "artifact_coverage_instruction": [
            "Produce artifacts for page evidence that is directly relevant to the question.",
            "If page_modality_diagnosis.mentions_chart is true, produce figure and numeric_fact candidate artifacts when visible in the page.",
            "If page_modality_diagnosis.mentions_table is true, produce table and numeric_fact candidate artifacts when visible in the page.",
            "If numeric values are visible and relevant to the question, produce numeric_fact candidate artifacts.",
            "Do not answer the question or phrase artifact content as a generated answer.",
            "Do not infer hidden values.",
            "If the chart/table/visual detail is not readable, add uncertain_or_unreadable instead of guessing.",
        ],
        "rules": [
            "Return exactly one PageArtifactOutput JSON object.",
            "Output strict RFC8259-style JSON only: one object, no markdown fences, no surrounding prose.",
            "The first output character must be { and the final output character must be }.",
            "Use only source_id values present in layout_blocks.",
            "Every artifact must have validation_status set to candidate.",
            "Do not generate an answer to the question.",
            "Keep artifact.content evidence-focused and non-generative.",
            "Do not include gold answers, baseline outputs, or source records.",
            "Do not create supports or contradicts edges.",
            "Do not create proof_trace, verified, answer_supported, or proof_used fields.",
            "For visual questions, output visual_observation artifacts only for visible, question-relevant evidence anchored to the page image.",
            "Return JSON only.",
        ],
    }

    return json.dumps(prompt_payload, ensure_ascii=False, indent=2)


def build_document_generic_artifact_compiler_user_prompt(
    canonical_record: Dict[str, Any],
    page_input: Dict[str, Any],
    schema_dict: Dict[str, Any],
) -> str:
    """Build a question-independent prompt for document-generic compilation."""

    document = canonical_record["document"]
    page_index = int(page_input["page_index"])
    prompt_payload = {
        "task": "Convert this single document page into candidate evidence artifacts.",
        "document": {
            "doc_id": document["doc_id"],
            "page_index": page_index,
            "page_number_one_based": page_index + 1,
        },
        "compilation_plan": {
            "compile_scope": "stage2_document_generic_single_page",
            "priority_pages": [],
            "compilation_reasons": [
                {
                    "page_index": page_index,
                    "reason_type": "document_generic_page_compilation",
                    "reason_text": "compile available page evidence without question conditioning",
                }
            ],
        },
        "page_requirement": {
            "explicit_page_constraint": False,
            "minimum_candidate_artifact": None,
            "instruction": "Include visible or readable page evidence as candidate artifacts; return artifacts=[] when no anchored evidence is available.",
        },
        "allowed_artifact_types": get_allowed_artifact_types(),
        "required_json_schema": schema_dict,
        "layout_blocks": page_input.get("layout_blocks", []),
        "page_text": page_input.get("page_text"),
        "numeric_evidence_candidates_from_page_text": _extract_numeric_evidence_candidates(page_input.get("page_text")),
        "artifact_coverage_instruction": [
            "Produce only high-confidence document-generic evidence artifacts; it is acceptable to return artifacts=[].",
            "Prefer atomic structured artifacts that can support retrieval: table_cell and numeric_fact first, then caption or figure when readable.",
            "For readable tables, extract individual cells or metric facts instead of one whole-table blob.",
            "For pages with readable tables, charts, measurements, counts, percentages, dates, totals, or specification values, emit numeric_fact and table_cell artifacts before any table descriptor.",
            "For each readable numeric table, emit 3 to 8 table_cell or numeric_fact artifacts for salient visible values, percentages, totals, measurements, or labeled rows.",
            "Use a table artifact only as a compact table-level descriptor after atomic values have been emitted; a table artifact must never replace numeric_fact or table_cell artifacts.",
            "If a page has readable numeric values, do not output only a table name, caption, section title, or broad table summary.",
            "If a table artifact is included, keep content under 120 characters and put detailed values into table_cell or numeric_fact artifacts.",
            "For a table_cell, normalized_content must include table_id, row_index, column_index, value_text, and any visible row_header or column_header.",
            "For a numeric_fact, normalized_content must include metric_name, row_label or row_header, column_label or column_header, value_text, unit or percent, normalized_value when possible, date_or_period when visible, source_text, and locator context.",
            "A numeric_fact without a concrete value_text, metric_name, and row/column/context label is invalid; omit it instead of outputting a broad summary.",
            "Use numeric_evidence_candidates_from_page_text as the preferred extraction targets when present; convert these snippets into numeric_fact or table_cell artifacts, not text_span artifacts.",
            "For tables with period, group, condition, or category columns, use the row label as row_label, the visible column header as column_label, and the numeric or categorical entry as value_text.",
            "For measurement tables, use the measured variable as metric_name or row_label and emit numeric_fact/table_cell artifacts for the visible condition, group, period, or category values.",
            "For a figure or caption, normalized_content must include figure_id or caption_id and the visible title/caption text when readable.",
            "When evidence comes from OCR text, put char_start and char_end in normalized_content using the provided layout block text.",
            "When evidence comes from image/table layout, include normalized_content.locator with locator_kind=bbox and bbox=[x0,y0,x1,y1] only if the element can be localized.",
            "Also put structured locator fields in locators: table_cell for table_cell artifacts, text_offset for OCR-backed numeric_fact/caption artifacts, figure_region for localized figure artifacts, and caption_block for caption artifacts.",
            "Each structured artifact must use a non-full-page source anchor whenever a text/table/layout block is available.",
            "Do not use full_page_image as the only locator for numeric_fact, table, table_cell, or caption artifacts.",
            "Do not put table_id, row_index, column_index, figure_id, caption_id, char_start, char_end, or bbox as top-level artifact fields; put them in normalized_content or locators.",
            "Do not answer any question and do not infer hidden values.",
            "If content cannot be localized or read, add uncertain_or_unreadable instead of guessing.",
        ],
        "structured_artifact_examples": [
            {
                "artifact_type": "table_cell",
                "modality": "table",
                "content": "Female respondents: 54%",
                "normalized_content": {
                    "table_id": "table_001",
                    "row_index": 2,
                    "column_index": 3,
                    "row_header": "Female",
                    "column_header": "Respondents",
                    "value_text": "54%"
                }
            },
            {
                "artifact_type": "numeric_fact",
                "modality": "numeric",
                "content": "Treatment group mean response time: 7.1 minutes.",
                "normalized_content": {
                    "metric_name": "mean response time",
                    "row_label": "Treatment group",
                    "column_label": "response time",
                    "value_text": "7.1",
                    "unit": "minutes",
                    "normalized_value": 7.1,
                    "date_or_period": "reported period",
                    "source_text": "Treatment group mean response time 7.1 minutes"
                }
            }
        ],
        "strong_eligibility_target": {
            "purpose": "Produce artifacts that can be used by artifact-aware retrieval without fallback.",
            "preferred_artifact_types": ["table_cell", "numeric_fact", "figure", "caption", "table"],
            "must_avoid_content_prefixes": ["Mock", "Placeholder", "Generic", "Candidate anchored to"],
            "required_properties": [
                "non_empty_visible_page_content",
                "source_anchors_from_layout_blocks",
                "provenance.sources_matching_source_anchors",
                "non_full_page_locator_when_available",
                "normalized_content.value_text_for_numeric_or_table_cell",
                "normalized_content.metric_name_row_label_column_label_unit_for_numeric_fact",
                "locators.table_cell_or_text_offset_or_bbox_or_caption_block_or_figure_region",
            ],
            "locator_examples": [
                {"locator_kind": "table_cell", "table_id": "table_001", "row_index": 2, "column_index": 3},
                {"locator_kind": "text_offset", "block_id": "p007_text_0002", "char_start": 120, "char_end": 137},
                {"locator_kind": "caption_block", "caption_id": "caption_001", "block_id": "p007_text_0004"},
                {"locator_kind": "figure_region", "figure_id": "fig_001", "bbox": [0.12, 0.18, 0.88, 0.62]},
            ],
        },
        "rules": [
            "Return exactly one PageArtifactOutput JSON object.",
            "Output strict RFC8259-style JSON only: one object, no markdown fences, no surrounding prose.",
            "The first output character must be { and the final output character must be }.",
            "Use only source_id values present in layout_blocks.",
            "Every artifact must have validation_status set to candidate.",
            "Every artifact must have non-empty content copied or tightly paraphrased from visible/readable page evidence.",
            "Do not satisfy table evidence with only broad table artifacts when readable cells or numeric values are visible.",
            "For tables containing readable measurements, counts, percentages, dates, totals, categories, or specification values, output atomic numeric_fact/table_cell artifacts; broad table summaries alone are invalid.",
            "Do not output text_span artifacts for numeric candidate snippets when numeric_fact or table_cell can represent the same evidence.",
            "Do not output table_cell artifacts without normalized_content.value_text.",
            "If the only candidate artifact would be a table title, caption, or section heading, either output atomic values from the same source block or return artifacts=[].",
            "Do not create a table artifact whose content is a long OCR dump of many rows.",
            "Do not output mock, placeholder, generic, or candidate boilerplate content.",
            "Do not include question text, generated answers, gold answers, baseline outputs, or source records.",
            "Do not create supports or contradicts edges.",
            "Do not create proof_trace, verified, answer_supported, or proof_used fields.",
            "Return JSON only.",
        ],
    }
    return json.dumps(prompt_payload, ensure_ascii=False, indent=2)


def _extract_numeric_evidence_candidates(page_text: Any, max_candidates: int = 18) -> list[Dict[str, Any]]:
    """Extract public-safe numeric snippets from Stage 2 OCR text for prompt focus."""

    if not isinstance(page_text, str) or not page_text.strip():
        return []
    raw_lines = [line.strip() for line in page_text.splitlines()]
    lines = [line for line in raw_lines if line]
    candidates: list[Dict[str, Any]] = []
    seen: set[str] = set()
    numeric_pattern = re.compile(r"(?:\$|\b\d[\d,]*(?:\.\d+)?\b|%|\(\s*\d)")
    header_pattern = re.compile(r"\b(year|revenue|sales|profit|income|margin|baseline|target|actual|result|percentage|percent|fiscal|202\d|200\d)\b", re.I)
    for index, line in enumerate(lines):
        if not numeric_pattern.search(line):
            continue
        window_lines = []
        for neighbor_index in range(max(0, index - 2), min(len(lines), index + 3)):
            neighbor = lines[neighbor_index]
            if neighbor_index == index or header_pattern.search(neighbor) or numeric_pattern.search(neighbor):
                window_lines.append(neighbor)
        snippet = " | ".join(window_lines)
        snippet = " ".join(snippet.split())
        if not snippet or snippet in seen:
            continue
        seen.add(snippet)
        candidates.append(
            {
                "line_index": index,
                "snippet": snippet[:500],
                "instruction": "Emit numeric_fact or table_cell artifacts with row_label, column_label, value_text, unit/percent, source_text, and locator.",
            }
        )
        if len(candidates) >= max_candidates:
            break
    return candidates


def _is_explicit_page_constraint(question_constraints: Dict[str, Any], page_index: int) -> bool:
    for page_ref in question_constraints.get("explicit_page_references", []):
        if page_ref.get("page_index_zero_based") == page_index:
            return True
    return False


def _build_page_requirement(page_input: Dict[str, Any], is_explicit_page: bool) -> Dict[str, Any]:
    _ = page_input
    return {
        "explicit_page_constraint": bool(is_explicit_page),
        "minimum_candidate_artifact": None,
        "instruction": "Only include question-relevant positive evidence artifacts anchored to the page; return artifacts=[] when the page has no such evidence.",
    }

# ---- from real_api_client.py ----


from typing import Any, Dict, Optional



class RealApiArtifactCompilerClient(ArtifactCompilerClient):
    """Real provider client guarded by ApiRunConfig and single-page policy."""

    def __init__(self, api_config: ApiRunConfig, provider: Optional[Any] = None) -> None:
        self.api_config = api_config
        self.provider = provider

    def generate_page_artifacts(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
        page_input: Dict[str, Any] | None = None,
    ) -> Dict[str, Any]:
        assert_real_api_allowed(self.api_config)
        provider = self.provider or self._build_provider()
        return _call_provider_generate_json(
            provider=provider,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            schema_dict=schema_dict,
            image_path=_page_image_path_allowed_by_route(page_input, self.api_config.image_payload_mode),
        )

    def _build_provider(self) -> Any:
        if self.api_config.provider in {"siliconflow", "custom", "compatible_chat"}:
            return CompatibleChatJsonProvider(self.api_config)
        raise ProviderNotConfiguredError(f"Provider {self.api_config.provider!r} is not implemented.")


def _page_image_path_allowed_by_route(
    page_input: Dict[str, Any] | None,
    image_payload_mode: str = "image_url",
) -> str | None:
    if not isinstance(page_input, dict):
        return None
    if image_payload_mode == "none":
        return None
    input_routes = page_input.get("input_routes")
    if input_routes is not None and "image" not in {str(route) for route in input_routes}:
        return None
    page_image_path = page_input.get("page_image_path")
    if not page_image_path:
        return None
    path = Path(page_image_path)
    if not path.is_file():
        return None
    return str(path)


def _call_provider_generate_json(
    provider: Any,
    system_prompt: str,
    user_prompt: str,
    schema_dict: Dict[str, Any],
    image_path: str | None,
) -> Dict[str, Any]:
    generate_json = provider.generate_json
    if image_path and _callable_accepts_keyword(generate_json, "image_path"):
        return generate_json(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            schema_dict=schema_dict,
            image_path=image_path,
        )
    return generate_json(system_prompt, user_prompt, schema_dict)


def _callable_accepts_keyword(callable_obj: Any, keyword: str) -> bool:
    try:
        parameters = inspect.signature(callable_obj).parameters.values()
    except (TypeError, ValueError):
        return False
    for parameter in parameters:
        if parameter.kind == inspect.Parameter.VAR_KEYWORD:
            return True
        if parameter.name == keyword:
            return True
    return False
