"""Consolidated Stage 2 module.

Generated by module consolidation; public behavior is preserved.
"""

from __future__ import annotations


# ---- from api_config.py ----


from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class ApiRunConfig:
    enable_real_api: bool = False
    provider: str = "siliconflow"
    model_name: Optional[str] = None
    max_pages: int = 1
    max_pages_total: Optional[int] = None
    max_pages_per_call: int = 1
    temperature: float = 0.0
    timeout_seconds: int = 120
    raw_output_dir: str | Path | None = None
    discard_log_dir: str | Path | None = None
    api_base_url: Optional[str] = None
    api_key_env_var: str = "SILICONFLOW_API_KEY"
    api_key: Optional[str] = field(default=None, repr=False)
    max_tokens: Optional[int] = None
    image_payload_mode: str = "image_url"


def assert_real_api_allowed(config: ApiRunConfig) -> None:
    """Enforce explicit single-page opt-in before any real API call."""

    if not config.enable_real_api:
        raise RuntimeError("Real API usage is disabled. Set enable_real_api=True explicitly.")
    if int(getattr(config, "max_pages_per_call", 1)) != 1:
        raise RuntimeError("Real provider calls are limited to max_pages_per_call=1.")
    max_pages_total = getattr(config, "max_pages_total", None)
    if max_pages_total is None:
        max_pages_total = getattr(config, "max_pages", None)
    if max_pages_total is None or int(max_pages_total) < 1:
        raise RuntimeError("Real API usage requires a finite positive max_pages_total.")
    if not config.model_name:
        raise RuntimeError("Real API usage requires a non-empty model_name.")

# ---- from provider_errors.py ----


from typing import Optional


class ProviderError(Exception):
    """Base class for provider adapter failures."""

    def __init__(self, message: str, raw_text: Optional[str] = None) -> None:
        super().__init__(message)
        self.raw_text = raw_text


class ProviderNotConfiguredError(ProviderError):
    """Raised when the requested provider is not configured or supported."""


class ProviderResponseFormatError(ProviderError):
    """Raised when a provider response cannot be parsed as a JSON object."""


class ProviderDependencyError(ProviderError):
    """Raised when a required provider runtime dependency is unavailable."""


class ProviderDisabledError(ProviderError):
    """Raised when real API usage is not explicitly enabled."""

# ---- from provider_client.py ----


import json
import base64
import inspect
import mimetypes
import os
from typing import Any, Dict, Optional
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen



DEFAULT_PROVIDER_BASE_URLS = {
    "siliconflow": "https://api.siliconflow.cn/v1",
}


class CompatibleChatJsonProvider:
    """Small HTTP adapter for providers exposing chat-completions style JSON responses."""

    def __init__(self, api_config: ApiRunConfig) -> None:
        self.api_config = api_config

    def generate_json(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
        image_path: str | Path | None = None,
    ) -> Dict[str, Any]:
        """Request one JSON object from a configured provider without validation or repair."""

        assert_real_api_allowed(self.api_config)
        api_key = _read_api_key(self.api_config)
        request_body = _build_request_body(
            model_name=str(self.api_config.model_name),
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            schema_dict=schema_dict,
            temperature=self.api_config.temperature,
            max_tokens=self.api_config.max_tokens,
            image_path=image_path,
            image_payload_mode=self.api_config.image_payload_mode,
        )
        request = Request(
            _resolve_chat_completions_url(self.api_config),
            data=json.dumps(request_body, ensure_ascii=False).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            method="POST",
        )
        try:
            with urlopen(request, timeout=self.api_config.timeout_seconds) as response:
                raw_text = response.read().decode("utf-8")
        except HTTPError as exc:
            raw_text = _read_error_body(exc)
            raise ProviderResponseFormatError(
                f"Provider HTTP error: {exc.code}",
                raw_text=raw_text,
            ) from exc
        except URLError as exc:
            raise ProviderError(f"Provider request failed: {exc.reason}") from exc

        return _parse_chat_completion_json(raw_text)


def _build_request_body(
    model_name: str,
    system_prompt: str,
    user_prompt: str,
    schema_dict: Dict[str, Any],
    temperature: float,
    max_tokens: Optional[int],
    image_path: str | Path | None = None,
    image_payload_mode: str = "image_url",
) -> Dict[str, Any]:
    _ = schema_dict
    payload_audit = describe_image_payload(image_path=image_path, image_payload_mode=image_payload_mode)
    request_body = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": _build_user_message_content(user_prompt, image_path, image_payload_mode)},
        ],
        "temperature": temperature,
        "stream": False,
        "response_format": {"type": "json_object"},
        "metadata": {
            "stage": "stage2_artifact_compilation",
            "schema_name": "page_artifact_output",
            "schema_version": "stage2_artifact_schema_v1",
            "image_payload_mode": image_payload_mode,
            "actual_image_payload_kind": payload_audit["actual_image_payload_kind"],
            "image_payload_sent": payload_audit["image_payload_sent"],
        },
    }
    if max_tokens is not None:
        request_body["max_tokens"] = max_tokens
    return request_body


def _build_user_message_content(
    user_prompt: str,
    image_path: str | Path | None = None,
    image_payload_mode: str = "image_url",
) -> Any:
    if not image_path or image_payload_mode == "none":
        return user_prompt
    if image_payload_mode not in {"image_url", "base64"}:
        raise ProviderError(f"Unsupported image_payload_mode: {image_payload_mode}")
    return [
        {"type": "text", "text": user_prompt},
        {"type": "image_url", "image_url": {"url": _build_image_data_url(image_path)}},
    ]


def describe_image_payload(
    image_path: str | Path | None,
    image_payload_mode: str = "image_url",
) -> Dict[str, Any]:
    """Return public-safe image payload audit metadata."""

    if not image_path or image_payload_mode == "none":
        return {"image_payload_mode": image_payload_mode, "actual_image_payload_kind": "none", "image_payload_sent": False}
    if image_payload_mode not in {"image_url", "base64"}:
        raise ProviderError(f"Unsupported image_payload_mode: {image_payload_mode}")
    if not Path(image_path).is_file():
        return {"image_payload_mode": image_payload_mode, "actual_image_payload_kind": "none", "image_payload_sent": False}
    return {
        "image_payload_mode": image_payload_mode,
        "actual_image_payload_kind": "base64_data_url",
        "image_payload_sent": True,
    }


def _build_image_data_url(image_path: str | Path) -> str:
    path = Path(image_path)
    if not path.is_file():
        raise ProviderError(f"Image payload path does not exist: {path}")
    mime_type = _guess_image_mime_type(path)
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def _guess_image_mime_type(path: Path) -> str:
    guessed_type, _ = mimetypes.guess_type(str(path))
    if guessed_type and guessed_type.startswith("image/"):
        return guessed_type
    suffix = path.suffix.lower()
    if suffix in {".jpg", ".jpeg"}:
        return "image/jpeg"
    if suffix == ".webp":
        return "image/webp"
    return "image/png"


def _read_api_key(api_config: ApiRunConfig) -> str:
    direct_api_key = getattr(api_config, "api_key", None)
    if direct_api_key:
        return str(direct_api_key)
    api_key = os.environ.get(api_config.api_key_env_var, "")
    if not api_key.strip():
        raise ProviderNotConfiguredError(
            f"Provider API key environment variable is not set: {api_config.api_key_env_var}"
        )
    return api_key


def _resolve_chat_completions_url(api_config: ApiRunConfig) -> str:
    base_url = api_config.api_base_url or os.environ.get("STAGE2_API_BASE_URL")
    if not base_url:
        base_url = DEFAULT_PROVIDER_BASE_URLS.get(api_config.provider)
    if not base_url:
        raise ProviderNotConfiguredError(
            f"Provider base URL is not configured for provider {api_config.provider!r}."
        )
    normalized_base = base_url.rstrip("/")
    if normalized_base.endswith("/chat/completions"):
        return normalized_base
    return f"{normalized_base}/chat/completions"


def _parse_chat_completion_json(raw_text: str) -> Dict[str, Any]:
    try:
        response_object = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        raise ProviderResponseFormatError("Provider response was not valid JSON.", raw_text=raw_text) from exc

    if isinstance(response_object, dict) and _looks_like_page_artifact_output(response_object):
        return response_object

    content = _extract_message_content(response_object)
    if isinstance(content, dict):
        return content
    if not isinstance(content, str):
        raise ProviderResponseFormatError("Provider response did not contain JSON text.", raw_text=raw_text)

    json_text = _strip_json_fence(content)
    try:
        parsed = json.loads(json_text)
    except json.JSONDecodeError as exc:
        raise ProviderResponseFormatError("Provider message content was not valid JSON.", raw_text=content) from exc
    if not isinstance(parsed, dict):
        raise ProviderResponseFormatError("Provider message JSON was not an object.", raw_text=content)
    return parsed


def _extract_message_content(response_object: Any) -> Optional[Any]:
    if not isinstance(response_object, dict):
        return None
    choices = response_object.get("choices")
    if not isinstance(choices, list) or not choices:
        return response_object.get("content")
    first_choice = choices[0]
    if not isinstance(first_choice, dict):
        return None
    message = first_choice.get("message")
    if isinstance(message, dict):
        content = message.get("content")
        if isinstance(content, list):
            return _join_content_parts(content)
        return content
    return first_choice.get("text")


def _join_content_parts(content_parts: list[Any]) -> str:
    text_parts = []
    for part in content_parts:
        if isinstance(part, dict) and isinstance(part.get("text"), str):
            text_parts.append(part["text"])
        elif isinstance(part, str):
            text_parts.append(part)
    return "".join(text_parts)


def _strip_json_fence(text: str) -> str:
    stripped = text.strip()
    fence = chr(96) * 3
    if stripped.startswith(fence):
        lines = stripped.splitlines()
        if lines and lines[0].startswith(fence):
            lines = lines[1:]
        if lines and lines[-1].strip() == fence:
            lines = lines[:-1]
        return "\n".join(lines).strip()
    return stripped


def _looks_like_page_artifact_output(value: Dict[str, Any]) -> bool:
    return {"doc_id", "page_index", "artifacts"}.issubset(value.keys())


def _read_error_body(error: HTTPError) -> str:
    try:
        return error.read().decode("utf-8")
    except Exception:
        return ""

# ---- from mock_artifact_outputs.py ----


from pathlib import Path
from typing import Any, Dict, List, Optional


MOCK_COMPILER_METADATA = {
    "compiler_name": "mock_artifact_output_builder",
    "compiler_version": "mock_stage2_dry_run",
}


def build_mock_page_artifact_output(
    doc_id: str,
    page_index: int,
    layout_blocks: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Build deterministic mock artifacts anchored to existing layout blocks."""

    full_page_block = _first_block_of_type(layout_blocks, "full_page_image")
    text_block = _first_block_of_type(layout_blocks, "text_block")
    artifacts: List[Dict[str, Any]] = []

    if full_page_block is not None:
        artifacts.append(_build_visual_observation(doc_id, page_index, full_page_block))
    if text_block is not None:
        artifacts.append(_build_text_span(doc_id, page_index, text_block))

    return {
        "doc_id": doc_id,
        "page_index": page_index,
        "artifacts": artifacts,
        "uncertain_or_unreadable": [],
    }


def _build_visual_observation(
    doc_id: str,
    page_index: int,
    block: Dict[str, Any],
) -> Dict[str, Any]:
    source_id = block["block_id"]
    return {
        "artifact_id": f"{_doc_stem(doc_id)}_p{page_index:03d}_visual_observation_0001",
        "doc_id": doc_id,
        "page_index": page_index,
        "artifact_type": "visual_observation",
        "modality": "image",
        "content": "Mock visual observation anchored to the full page image.",
        "normalized_content": {
            "observation_scope": "full_page",
            "presence": "undetermined",
        },
        "source_anchors": [
            {
                "source_id": source_id,
                "anchor_type": "full_page_image",
                "page_index": page_index,
                "bbox": None,
            }
        ],
        "provenance": {
            "op": "ATOM",
            "sources": [source_id],
        },
        "validation_status": "candidate",
        "compiler_metadata": dict(MOCK_COMPILER_METADATA),
    }


def _build_text_span(
    doc_id: str,
    page_index: int,
    block: Dict[str, Any],
) -> Dict[str, Any]:
    source_id = block["block_id"]
    return {
        "artifact_id": f"{_doc_stem(doc_id)}_p{page_index:03d}_text_span_0001",
        "doc_id": doc_id,
        "page_index": page_index,
        "artifact_type": "text_span",
        "modality": "text",
        "content": "Mock text span anchored to a text block.",
        "normalized_content": {},
        "source_anchors": [
            {
                "source_id": source_id,
                "anchor_type": "text_block",
                "page_index": page_index,
                "bbox": None,
            }
        ],
        "provenance": {
            "op": "ATOM",
            "sources": [source_id],
        },
        "validation_status": "candidate",
        "compiler_metadata": dict(MOCK_COMPILER_METADATA),
    }


def _first_block_of_type(
    layout_blocks: List[Dict[str, Any]],
    block_type: str,
) -> Optional[Dict[str, Any]]:
    for block in layout_blocks:
        if block.get("block_type") == block_type:
            return block
    return None


def _doc_stem(doc_id: str) -> str:
    return Path(doc_id).name.removesuffix(".pdf")

# ---- from compiler_client.py ----


import json
from typing import Any, Dict



class ArtifactCompilerClient:
    """Abstract compiler client interface."""

    def generate_page_artifacts(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
    ) -> Dict[str, Any]:
        raise NotImplementedError


class FakeArtifactCompilerClient(ArtifactCompilerClient):
    """Offline fake compiler client used by default tests and dry runs."""

    def generate_page_artifacts(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
    ) -> Dict[str, Any]:
        _ = system_prompt
        _ = schema_dict
        prompt_payload = json.loads(user_prompt)
        document = prompt_payload["document"]
        return build_mock_page_artifact_output(
            doc_id=document["doc_id"],
            page_index=document["page_index"],
            layout_blocks=prompt_payload.get("layout_blocks", []),
        )


class RealArtifactCompilerClient(ArtifactCompilerClient):
    """Real compiler client skeleton guarded by enable_real_api."""

    def __init__(self, enable_real_api: bool = False, provider_config: Dict[str, Any] | None = None) -> None:
        self.enable_real_api = enable_real_api
        self.provider_config = provider_config or {}

    def generate_page_artifacts(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
    ) -> Dict[str, Any]:
        if not self.enable_real_api:
            raise RuntimeError("Real artifact compiler API is disabled. Pass enable_real_api=True explicitly.")
        raise NotImplementedError("Real provider integration is intentionally not implemented in Step 5.")

# ---- from compiler_prompt.py ----


import json
from typing import Any, Dict

from .artifact_schema import get_allowed_artifact_types


def build_artifact_compiler_system_prompt() -> str:
    """Build the system prompt for a constrained artifact compiler."""

    return "\n".join(
        [
            "You are an evidence artifact compiler.",
            "Convert one document page into typed evidence artifacts.",
            "Do not answer the question.",
            "Do not use gold answers.",
            "Do not infer unsupported facts.",
            "Artifact content must describe page evidence, not a generated answer.",
            "Every artifact must cite source_anchors from the provided layout_blocks.",
            "Artifact status must be candidate before validation.",
            "Do not generate supports / contradicts edges.",
            "Do not generate proof_trace.",
            "Do not output verified / answer_supported / proof_used.",
            "If uncertain, write uncertain_or_unreadable.",
            "Return JSON only.",
        ]
    )


def build_artifact_compiler_user_prompt(
    canonical_record: Dict[str, Any],
    page_input: Dict[str, Any],
    schema_dict: Dict[str, Any],
) -> str:
    """Build the user prompt from compiler-safe canonical fields and page input."""

    document = canonical_record["document"]
    question = canonical_record["question"]
    question_constraints = canonical_record.get("question_constraints", {})
    compilation_plan = canonical_record.get("compilation_plan", {})
    page_index = int(page_input["page_index"])
    is_explicit_page = _is_explicit_page_constraint(question_constraints, page_index)
    page_requirement = _build_page_requirement(page_input, is_explicit_page)
    page_modality_diagnosis = page_input.get("page_modality_diagnosis", {})

    prompt_payload = {
        "task": "Convert this single page into candidate evidence artifacts.",
        "document": {
            "doc_id": document["doc_id"],
            "page_index": page_index,
            "page_number_one_based": page_index + 1,
        },
        "question": {
            "text": question.get("text"),
            "answer_format": question.get("answer_format"),
        },
        "question_constraints": question_constraints,
        "compilation_plan": {
            "compile_scope": compilation_plan.get("compile_scope"),
            "priority_pages": compilation_plan.get("priority_pages", []),
            "compilation_reasons": compilation_plan.get("compilation_reasons", []),
        },
        "page_requirement": page_requirement,
        "page_modality_diagnosis": page_modality_diagnosis,
        "allowed_artifact_types": get_allowed_artifact_types(),
        "required_json_schema": schema_dict,
        "layout_blocks": page_input.get("layout_blocks", []),
        "page_text": page_input.get("page_text"),
        "artifact_coverage_instruction": [
            "Produce artifacts for page evidence that is directly relevant to the question.",
            "If page_modality_diagnosis.mentions_chart is true, produce figure and numeric_fact candidate artifacts when visible in the page.",
            "If page_modality_diagnosis.mentions_table is true, produce table and numeric_fact candidate artifacts when visible in the page.",
            "If numeric values are visible and relevant to the question, produce numeric_fact candidate artifacts.",
            "Do not answer the question or phrase artifact content as a generated answer.",
            "Do not infer hidden values.",
            "If the chart/table/visual detail is not readable, add uncertain_or_unreadable instead of guessing.",
        ],
        "rules": [
            "Return exactly one PageArtifactOutput JSON object.",
            "Use only source_id values present in layout_blocks.",
            "Every artifact must have validation_status set to candidate.",
            "Do not generate an answer to the question.",
            "Keep artifact.content evidence-focused and non-generative.",
            "Do not include gold answers, baseline outputs, or source records.",
            "Do not create supports or contradicts edges.",
            "Do not create proof_trace, verified, answer_supported, or proof_used fields.",
            "For visual questions, output visual_observation artifacts only for visible, question-relevant evidence anchored to the page image.",
            "Return JSON only.",
        ],
    }

    return json.dumps(prompt_payload, ensure_ascii=False, indent=2)


def build_document_generic_artifact_compiler_user_prompt(
    canonical_record: Dict[str, Any],
    page_input: Dict[str, Any],
    schema_dict: Dict[str, Any],
) -> str:
    """Build a question-independent prompt for document-generic compilation."""

    document = canonical_record["document"]
    page_index = int(page_input["page_index"])
    prompt_payload = {
        "task": "Convert this single document page into candidate evidence artifacts.",
        "document": {
            "doc_id": document["doc_id"],
            "page_index": page_index,
            "page_number_one_based": page_index + 1,
        },
        "compilation_plan": {
            "compile_scope": "stage2_document_generic_single_page",
            "priority_pages": [],
            "compilation_reasons": [
                {
                    "page_index": page_index,
                    "reason_type": "document_generic_page_compilation",
                    "reason_text": "compile available page evidence without question conditioning",
                }
            ],
        },
        "page_requirement": {
            "explicit_page_constraint": False,
            "minimum_candidate_artifact": None,
            "instruction": "Include visible or readable page evidence as candidate artifacts; return artifacts=[] when no anchored evidence is available.",
        },
        "allowed_artifact_types": get_allowed_artifact_types(),
        "required_json_schema": schema_dict,
        "layout_blocks": page_input.get("layout_blocks", []),
        "page_text": page_input.get("page_text"),
        "artifact_coverage_instruction": [
            "Produce document-generic evidence artifacts for visible or readable page content.",
            "For text, tables, captions, figures, and numeric values, cite source_anchors from layout_blocks.",
            "Do not answer any question.",
            "Do not infer hidden values.",
            "If content cannot be localized or read, add uncertain_or_unreadable instead of guessing.",
        ],
        "rules": [
            "Return exactly one PageArtifactOutput JSON object.",
            "Use only source_id values present in layout_blocks.",
            "Every artifact must have validation_status set to candidate.",
            "Do not include question text, generated answers, gold answers, baseline outputs, or source records.",
            "Do not create supports or contradicts edges.",
            "Do not create proof_trace, verified, answer_supported, or proof_used fields.",
            "Return JSON only.",
        ],
    }
    return json.dumps(prompt_payload, ensure_ascii=False, indent=2)


def _is_explicit_page_constraint(question_constraints: Dict[str, Any], page_index: int) -> bool:
    for page_ref in question_constraints.get("explicit_page_references", []):
        if page_ref.get("page_index_zero_based") == page_index:
            return True
    return False


def _build_page_requirement(page_input: Dict[str, Any], is_explicit_page: bool) -> Dict[str, Any]:
    _ = page_input
    return {
        "explicit_page_constraint": bool(is_explicit_page),
        "minimum_candidate_artifact": None,
        "instruction": "Only include question-relevant positive evidence artifacts anchored to the page; return artifacts=[] when the page has no such evidence.",
    }

# ---- from real_api_client.py ----


from typing import Any, Dict, Optional



class RealApiArtifactCompilerClient(ArtifactCompilerClient):
    """Real provider client guarded by ApiRunConfig and single-page policy."""

    def __init__(self, api_config: ApiRunConfig, provider: Optional[Any] = None) -> None:
        self.api_config = api_config
        self.provider = provider

    def generate_page_artifacts(
        self,
        system_prompt: str,
        user_prompt: str,
        schema_dict: Dict[str, Any],
        page_input: Dict[str, Any] | None = None,
    ) -> Dict[str, Any]:
        assert_real_api_allowed(self.api_config)
        provider = self.provider or self._build_provider()
        return _call_provider_generate_json(
            provider=provider,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            schema_dict=schema_dict,
            image_path=_page_image_path_allowed_by_route(page_input, self.api_config.image_payload_mode),
        )

    def _build_provider(self) -> Any:
        if self.api_config.provider in {"siliconflow", "custom", "compatible_chat"}:
            return CompatibleChatJsonProvider(self.api_config)
        raise ProviderNotConfiguredError(f"Provider {self.api_config.provider!r} is not implemented.")


def _page_image_path_allowed_by_route(
    page_input: Dict[str, Any] | None,
    image_payload_mode: str = "image_url",
) -> str | None:
    if not isinstance(page_input, dict):
        return None
    if image_payload_mode == "none":
        return None
    input_routes = page_input.get("input_routes")
    if input_routes is not None and "image" not in {str(route) for route in input_routes}:
        return None
    page_image_path = page_input.get("page_image_path")
    if not page_image_path:
        return None
    path = Path(page_image_path)
    if not path.is_file():
        return None
    return str(path)


def _call_provider_generate_json(
    provider: Any,
    system_prompt: str,
    user_prompt: str,
    schema_dict: Dict[str, Any],
    image_path: str | None,
) -> Dict[str, Any]:
    generate_json = provider.generate_json
    if image_path and _callable_accepts_keyword(generate_json, "image_path"):
        return generate_json(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            schema_dict=schema_dict,
            image_path=image_path,
        )
    return generate_json(system_prompt, user_prompt, schema_dict)


def _callable_accepts_keyword(callable_obj: Any, keyword: str) -> bool:
    try:
        parameters = inspect.signature(callable_obj).parameters.values()
    except (TypeError, ValueError):
        return False
    for parameter in parameters:
        if parameter.kind == inspect.Parameter.VAR_KEYWORD:
            return True
        if parameter.name == keyword:
            return True
    return False
