"""Consolidated Stage 2 module.

Generated by module consolidation; public behavior is preserved.
"""

from __future__ import annotations


# ---- from batch_page_selector.py ----


from typing import Any, Dict, List, Mapping

from .index_builder import build_page_source, get_valid_explicit_page_indices


SELECTION_REASONS = (
    "valid_explicit_page_with_image",
    "image_top_10_first_available",
    "retrieval_union_first_available",
)


def select_pages_for_small_batch(
    stage2_records: list[dict],
    max_pages: int,
    extract_root: str = "tmp/MMLongBench",
) -> list[dict]:
    """Select up to max_pages legal page candidates without using eval fields."""

    max_pages = int(max_pages)
    if max_pages < 1:
        return []

    selected: List[Dict[str, Any]] = []
    for record_index, record in enumerate(stage2_records):
        if len(selected) >= max_pages:
            break
        candidate = select_one_page_from_record(record, record_index, extract_root)
        if candidate is not None:
            selected.append(candidate)
    return selected


def select_one_page_from_record(
    record: Mapping[str, Any],
    record_index: int,
    extract_root: str = "tmp/MMLongBench",
) -> Dict[str, Any] | None:
    stage2 = record.get("stage2", {})
    if not isinstance(stage2, dict):
        return None
    if not stage2.get("preflight", {}).get("passed", False):
        return None

    route_pages = candidate_route_pages(stage2)
    image_top_pages = candidate_route_pages(stage2, required_route="image")
    valid_explicit_pages = [
        page_index for page_index in get_valid_explicit_page_indices(record, extract_root) if page_index in route_pages
    ]

    for page_index in valid_explicit_pages:
        source = build_page_source(str(record.get("doc_id")), extract_root, page_index)
        if page_source_is_eligible(source):
            return build_selected_page(record, record_index, page_index, source, "valid_explicit_page_with_image")

    for page_index in image_top_pages:
        source = build_page_source(str(record.get("doc_id")), extract_root, page_index)
        if page_source_is_eligible(source):
            return build_selected_page(record, record_index, page_index, source, "image_top_10_first_available")

    for page_index in route_pages:
        source = build_page_source(str(record.get("doc_id")), extract_root, page_index)
        if page_source_is_eligible(source):
            return build_selected_page(record, record_index, page_index, source, "retrieval_union_first_available")

    return None


def page_source_is_eligible(page_source: Mapping[str, Any] | None) -> bool:
    return bool(
        page_source
        and page_source.get("has_page_image")
        and page_source.get("page_image_path")
        and page_source.get("layout_block_ids")
    )


def candidate_route_pages(stage2: Mapping[str, Any], required_route: str | None = None) -> List[int]:
    pages: List[int] = []
    for route in stage2.get("candidate_page_routes", []) or []:
        if not isinstance(route, dict) or route.get("page_index") is None:
            continue
        routes = route.get("routes", [])
        if required_route is not None and required_route not in routes:
            continue
        pages.append(int(route["page_index"]))
    return pages


def build_selected_page(
    record: Mapping[str, Any],
    record_index: int,
    page_index: int,
    page_source: Mapping[str, Any],
    selection_reason: str,
) -> Dict[str, Any]:
    return {
        "record_index": int(record_index),
        "doc_id": record.get("doc_id"),
        "question": record.get("question"),
        "answer_format": record.get("answer_format"),
        "page_index": int(page_index),
        "page_number_one_based": int(page_index) + 1,
        "selection_reason": selection_reason,
        "page_image_path": page_source.get("page_image_path"),
        "page_text_path": page_source.get("page_text_path"),
        "layout_block_ids": list(page_source.get("layout_block_ids", [])),
        "stage2": record.get("stage2", {}),
    }

# ---- from crossdoc_batch_selector.py ----


from typing import Any, Dict, Iterable, List, Mapping

from .index_builder import build_page_source, get_valid_explicit_page_indices


SELECTION_REASONS = (
    "valid_explicit_page_with_image",
    "image_top_10_first_available",
    "retrieval_union_first_available",
)


def select_crossdoc_pages_for_batch(
    stage2_records: list[dict],
    max_docs: int = 5,
    max_pages_per_doc: int = 2,
    max_pages: int = 10,
    extract_root: str = "tmp/MMLongBench",
) -> list[dict]:
    """Select legal cross-document page candidates without using eval fields."""

    max_docs = max(0, int(max_docs))
    max_pages_per_doc = max(0, int(max_pages_per_doc))
    max_pages = max(0, int(max_pages))
    if not max_docs or not max_pages_per_doc or not max_pages:
        return []

    selected: List[Dict[str, Any]] = []
    doc_counts: Dict[str, int] = {}
    selected_pages_by_doc: Dict[str, set[int]] = {}

    for record_index, record in enumerate(stage2_records):
        if len(selected) >= max_pages:
            break
        doc_id = record.get("doc_id")
        if not doc_id:
            continue
        doc_id = str(doc_id)
        if doc_id not in doc_counts and len(doc_counts) >= max_docs:
            continue
        if doc_counts.get(doc_id, 0) >= max_pages_per_doc:
            continue

        for page_index, reason in _prioritized_page_candidates(record, extract_root):
            if len(selected) >= max_pages:
                break
            if doc_id not in doc_counts and len(doc_counts) >= max_docs:
                break
            if doc_counts.get(doc_id, 0) >= max_pages_per_doc:
                break
            if page_index in selected_pages_by_doc.get(doc_id, set()):
                continue

            source = build_page_source(doc_id, extract_root, page_index)
            if not _page_source_is_eligible(source):
                continue

            selected.append(_build_selected_page(record, record_index, page_index, source, reason))
            doc_counts[doc_id] = doc_counts.get(doc_id, 0) + 1
            selected_pages_by_doc.setdefault(doc_id, set()).add(page_index)

    return selected


def _prioritized_page_candidates(record: Mapping[str, Any], extract_root: str) -> Iterable[tuple[int, str]]:
    stage2 = record.get("stage2", {})
    if not isinstance(stage2, dict):
        return []
    if not stage2.get("preflight", {}).get("passed", False):
        return []
    route_pages = _candidate_route_pages(stage2)
    valid_explicit_pages = [
        page_index for page_index in get_valid_explicit_page_indices(record, extract_root) if page_index in route_pages
    ]

    seen: set[int] = set()
    prioritized_groups = [
        (valid_explicit_pages, "valid_explicit_page_with_image"),
        (_candidate_route_pages(stage2, required_route="image"), "image_top_10_first_available"),
        (route_pages, "retrieval_union_first_available"),
    ]
    candidates: List[tuple[int, str]] = []
    for page_indices, reason in prioritized_groups:
        for page_index in page_indices:
            if page_index in seen:
                continue
            seen.add(page_index)
            candidates.append((page_index, reason))
    return candidates


def _candidate_route_pages(stage2: Mapping[str, Any], required_route: str | None = None) -> List[int]:
    pages: List[int] = []
    for route in stage2.get("candidate_page_routes", []) or []:
        if not isinstance(route, dict) or route.get("page_index") is None:
            continue
        routes = route.get("routes", [])
        if required_route is not None and required_route not in routes:
            continue
        pages.append(int(route["page_index"]))
    return pages


def _page_source_is_eligible(page_source: Mapping[str, Any] | None) -> bool:
    return bool(
        page_source
        and page_source.get("has_page_image") is True
        and page_source.get("page_image_path")
        and page_source.get("layout_block_ids")
    )


def _build_selected_page(
    record: Mapping[str, Any],
    record_index: int,
    page_index: int,
    page_source: Mapping[str, Any],
    selection_reason: str,
) -> Dict[str, Any]:
    return {
        "record_index": int(record_index),
        "doc_id": record.get("doc_id"),
        "question": record.get("question"),
        "page_index": int(page_index),
        "page_number_one_based": int(page_index) + 1,
        "selection_reason": selection_reason,
        "page_image_path": page_source.get("page_image_path"),
        "page_text_path": page_source.get("page_text_path"),
        "layout_block_ids": list(page_source.get("layout_block_ids", [])),
        "stage2": record.get("stage2", {}),
    }

# ---- from page_modality_diagnosis.py ----


import re
from typing import Any, Dict, Mapping


CHART_TERMS = ("chart", "graph", "plot")
TABLE_TERMS = ("table", "tabular", "spreadsheet")
FIGURE_TERMS = ("figure", "image", "picture", "photo", "diagram", "map")
VISUAL_TERMS = CHART_TERMS + TABLE_TERMS + FIGURE_TERMS + (
    "handwritten",
    "handwriting",
    "color",
    "colour",
    "visual",
)
NUMERIC_PATTERNS = (
    r"\bhow\s+much\b",
    r"\bhow\s+many\b",
    r"\bpercent\b",
    r"\bpercentage\b",
    r"\bnumber\b",
    r"\bamount\b",
    r"\bvalue\b",
    r"\byear\b",
)


def diagnose_page_modality_from_question_and_preflight(
    record: dict,
    page_context: dict,
    page_index: int,
) -> dict:
    """Derive non-gold prompt guidance from question text and runtime page metadata."""

    question_text = _question_text(record, page_context).lower()
    page_source = _page_source(page_context, page_index)
    has_page_image = bool(page_source.get("has_page_image") and page_source.get("page_image_path"))
    mentions_chart = _contains_any(question_text, CHART_TERMS)
    mentions_table = _contains_any(question_text, TABLE_TERMS)
    mentions_figure = _contains_any(question_text, FIGURE_TERMS)
    mentions_numeric_value = any(re.search(pattern, question_text) for pattern in NUMERIC_PATTERNS)
    requires_visual_reasoning = (
        mentions_chart
        or mentions_table
        or mentions_figure
        or _contains_any(question_text, VISUAL_TERMS)
    )

    recommended_artifact_types: list[str] = []
    if requires_visual_reasoning and has_page_image:
        recommended_artifact_types.append("visual_observation")
    if mentions_chart:
        recommended_artifact_types.extend(["figure", "numeric_fact"])
    if mentions_table:
        recommended_artifact_types.extend(["table", "numeric_fact"])
    if mentions_figure:
        recommended_artifact_types.extend(["figure", "caption"])
    if mentions_numeric_value:
        recommended_artifact_types.append("numeric_fact")

    return {
        "requires_visual_reasoning": bool(requires_visual_reasoning),
        "mentions_chart": bool(mentions_chart),
        "mentions_table": bool(mentions_table),
        "mentions_figure": bool(mentions_figure),
        "mentions_numeric_value": bool(mentions_numeric_value),
        "has_page_image": bool(has_page_image),
        "recommended_artifact_types": _dedupe_preserve_order(recommended_artifact_types),
    }


def _question_text(record: Mapping[str, Any], page_context: Mapping[str, Any]) -> str:
    question = record.get("question")
    if isinstance(question, dict):
        return str(question.get("text") or "")
    if question is not None:
        return str(question)
    return str(page_context.get("question") or "")


def _page_source(page_context: Mapping[str, Any], page_index: int) -> dict:
    for source in page_context.get("page_sources", []) or []:
        if not isinstance(source, dict):
            continue
        try:
            if int(source.get("page_index")) == int(page_index):
                return source
        except (TypeError, ValueError):
            continue
    return {}


def _contains_any(text: str, terms: tuple[str, ...]) -> bool:
    return any(re.search(rf"\b{re.escape(term)}\b", text) for term in terms)


def _dedupe_preserve_order(values: list[str]) -> list[str]:
    result = []
    seen = set()
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result

# ---- from trial_candidate_selector.py ----


from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional

from .index_builder import read_json_or_jsonl_records
from .index_builder import normalize_record
from .page_input import prepare_pages_for_compilation
from .index_builder import (
    OUT_OF_RANGE_ERROR,
    apply_explicit_page_range_validation_to_canonical_record,
    infer_document_page_count,
)


SELECTION_REASONS = [
    "valid_explicit_page_with_image",
    "image_top1_with_image",
    "retrieval_union_first_image",
]


def select_single_page_trial_candidate(
    sample_path: str | Path,
    dataset_name: str,
    extract_root: str | Path,
    config_path: str | Path | None = None,
    max_records: int | None = None,
) -> Dict[str, Any]:
    """Select one legal single-page real-API smoke-test candidate.

    The selector is deterministic and uses only question constraints, retrieval
    rankings, inferred page counts, and extracted page sources. It does not use
    gold answers, evidence pages, baseline outputs, or any real provider call.
    """

    _ = dataset_name
    _ = config_path
    records = read_json_or_jsonl_records(sample_path)
    limited_records = records[: int(max_records)] if max_records is not None else records

    stats = {
        "scanned_records": 0,
        "num_out_of_range_explicit_pages": 0,
        "num_missing_page_sources": 0,
    }
    candidates: List[Dict[str, Any]] = []

    for record_index, source_record in enumerate(limited_records):
        stats["scanned_records"] += 1
        candidates.extend(
            _collect_record_candidates(
                source_record=source_record,
                record_index=record_index,
                extract_root=extract_root,
                stats=stats,
            )
        )

    selected = _select_best_candidate(candidates)
    return {
        "selection_passed": selected is not None,
        "blocking_reasons": [] if selected is not None else ["no_valid_single_page_trial_candidate"],
        "selected": selected,
        "selection_policy": _selection_policy(),
        "extract_root": str(extract_root),
        **stats,
    }


def _collect_record_candidates(
    source_record: Mapping[str, Any],
    record_index: int,
    extract_root: str | Path,
    stats: Dict[str, int],
) -> List[Dict[str, Any]]:
    normalized = normalize_record(strip_eval_only_fields(source_record))
    canonical_record = normalized["canonical_record"]
    doc_id = canonical_record["document"]["doc_id"]
    page_count_info = infer_document_page_count(
        doc_id=doc_id,
        pdf_root=None,
        extract_root=extract_root,
    )
    validation = apply_explicit_page_range_validation_to_canonical_record(
        canonical_record,
        page_count_info,
    )
    stats["num_out_of_range_explicit_pages"] += sum(
        1
        for ref in validation.get("invalid_explicit_page_references", [])
        if ref.get("error_type") == OUT_OF_RANGE_ERROR
    )

    prepared_result = prepare_pages_for_compilation(canonical_record, extract_root)
    pages_by_index = {
        int(page["page_index"]): page
        for page in prepared_result.get("pages", [])
    }
    pages_to_compile = [
        int(page_index)
        for page_index in canonical_record.get("compilation_plan", {}).get("pages_to_compile", [])
    ]
    compile_order = {page_index: order for order, page_index in enumerate(pages_to_compile)}
    valid_explicit_pages = [
        int(page_index)
        for page_index in canonical_record.get("candidate_pool", {}).get("explicit_constraint_pages_valid", [])
    ]
    invalid_explicit_pages = {
        int(ref["page_index_zero_based"])
        for ref in validation.get("invalid_explicit_page_references", [])
        if ref.get("page_index_zero_based") is not None
    }

    candidates: List[Dict[str, Any]] = []
    for page_index in pages_to_compile:
        page = pages_by_index.get(page_index)
        if page is None or not _has_any_page_source(page):
            stats["num_missing_page_sources"] += 1
            continue
        if page_index in invalid_explicit_pages:
            continue
        if not _page_index_in_range(page_index, page_count_info):
            continue
        if not _page_passes_preflight(page, page_index):
            continue

        reason = _selection_reason(
            canonical_record=canonical_record,
            page_index=page_index,
            valid_explicit_pages=valid_explicit_pages,
            has_explicit_page_references=_has_explicit_page_references(canonical_record),
        )
        if reason is None:
            continue
        candidates.append(
            _build_candidate(
                normalized=normalized,
                canonical_record=canonical_record,
                page=page,
                record_index=record_index,
                page_index=page_index,
                selection_reason=reason,
                compile_order=compile_order.get(page_index, len(compile_order)),
            )
        )

    return candidates


def strip_eval_only_fields(source_record: Mapping[str, Any]) -> Dict[str, Any]:
    blocked_keys = {
        "answer",
        "evidence_pages",
        "evidence_sources",
        "ans_mmlb-MDocAgent",
        "binary_correctness",
        "gold_annotation",
        "baseline_outputs",
    }
    sanitized = {
        key: value
        for key, value in dict(source_record).items()
        if key not in blocked_keys
    }
    canonical = sanitized.get("canonical_record")
    if isinstance(canonical, dict):
        clean_canonical = dict(canonical)
        clean_canonical.pop("gold_annotation", None)
        clean_canonical.pop("baseline_outputs", None)
        clean_canonical.pop("source_record", None)
        sanitized["canonical_record"] = clean_canonical
    return sanitized


def _selection_reason(
    canonical_record: Dict[str, Any],
    page_index: int,
    valid_explicit_pages: List[int],
    has_explicit_page_references: bool,
) -> Optional[str]:
    if page_index in valid_explicit_pages:
        return "valid_explicit_page_with_image"

    image_pages = _ranked_page_indices(canonical_record, "image")
    if not has_explicit_page_references and image_pages and page_index == image_pages[0]:
        return "image_top1_with_image"

    return "retrieval_union_first_image"


def _has_explicit_page_references(canonical_record: Dict[str, Any]) -> bool:
    return bool(
        canonical_record.get("question_constraints", {}).get("explicit_page_references", [])
    )


def _build_candidate(
    normalized: Dict[str, Any],
    canonical_record: Dict[str, Any],
    page: Dict[str, Any],
    record_index: int,
    page_index: int,
    selection_reason: str,
    compile_order: int,
) -> Dict[str, Any]:
    layout_block_ids = [
        str(block["block_id"])
        for block in page.get("layout_blocks", [])
        if block.get("block_id")
    ]
    return {
        "record_index": record_index,
        "record_id": normalized.get("record_id"),
        "doc_id": canonical_record["document"]["doc_id"],
        "question": canonical_record["question"]["text"],
        "page_index": page_index,
        "page_number_one_based": page_index + 1,
        "selection_reason": selection_reason,
        "page_image_path": page.get("page_image_path"),
        "page_text_path": page.get("page_text_path"),
        "layout_block_ids": layout_block_ids,
        "_priority_rank": SELECTION_REASONS.index(selection_reason),
        "_compile_order": compile_order,
    }


def _select_best_candidate(candidates: Iterable[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    ordered = sorted(
        candidates,
        key=lambda item: (
            int(item["_priority_rank"]),
            int(item["record_index"]),
            int(item["_compile_order"]),
        ),
    )
    if not ordered:
        return None
    selected = dict(ordered[0])
    selected.pop("_priority_rank", None)
    selected.pop("_compile_order", None)
    return selected


def _ranked_page_indices(canonical_record: Dict[str, Any], retrieval_key: str) -> List[int]:
    return [
        int(item["page_index"])
        for item in canonical_record.get("retrieval", {}).get(retrieval_key, {}).get("ranked_pages_unique", [])
    ]


def _has_any_page_source(page: Dict[str, Any]) -> bool:
    return bool(page.get("has_page_image") or page.get("has_page_text"))


def _page_passes_preflight(page: Dict[str, Any], page_index: int) -> bool:
    if not page.get("has_page_image"):
        return False
    layout_block_ids = [block.get("block_id") for block in page.get("layout_blocks", [])]
    expected_full_page_id = f"p{page_index:03d}_full_page_image"
    return bool(layout_block_ids) and expected_full_page_id in layout_block_ids


def _page_index_in_range(page_index: int, page_count_info: Dict[str, Any]) -> bool:
    page_count = page_count_info.get("page_count")
    if page_count is not None:
        return 0 <= page_index < int(page_count)
    available_indices = {int(index) for index in page_count_info.get("available_page_indices", [])}
    return page_index in available_indices


def _selection_policy() -> Dict[str, Any]:
    return {
        "priority_order": list(SELECTION_REASONS),
        "uses_gold_answer": False,
        "uses_gold_evidence_pages": False,
        "uses_baseline_correctness": False,
    }
